### ISSUE TITLE
[Feature Request]Support Dora

### ISSUE THREAD

**Issue by sdbds** [kohya-ss/sd-scripts#1127]
paper:https://arxiv.org/pdf/2402.09353.pdf
code:https://github.com/catid/dora/blob/main/dora.py

**Comment by gesen2egee** [comment]
it had been supported by lycoris dev?

**Comment by Visual-Synthesizer** [comment]
Where supported?

**Comment by SlZeroth** [comment]
+1

**Comment by SlZeroth** [comment]
@sdbds did you solve it? I successfully trained lora. but I cant inference with it, because webui and diffusers not support load dora

**Comment by gesen2egee** [comment]
train: 
kohya requestment.txt  lycoris_lora==2.2.0
--network_args "dora_wd=True"

inference:
webui use this PR
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15239

You can replace it
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/9f2ae1cb85015ee3cc79f1de92641032df154d5b/extensions-builtin/Lora/network.py

**Comment by SlZeroth** [comment]
--network_module=lycoris.kohya --network_args "algo=lora" "dora_wd=True" is it right? 
because I got error in webui "Networks with errors: lora (956)"

**Comment by gesen2egee** [comment]
try "algo=locon"? but it may alias

**Comment by SlZeroth** [comment]
yes I replaced to https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/9f2ae1cb85015ee3cc79f1de92641032df154d5b/extensions-builtin/Lora/network.py but webui got error 

<img width="317" alt="image" src="https://github.com/kohya-ss/sd-scripts/assets/8098724/3c616ce0-8669-4529-823f-9f6d0ff1310f">

I dont know about reason why. I trying to train again with -network_args "algo=locon" "dora_wd=True" now

**Comment by gesen2egee** [comment]
I also dont know about reason why.
If you still have problem
Can join Lycoris DC
https://discord.gg/VtTFKrj9gJ

**Comment by NineMeowICT** [comment]
> I dont know about reason why. I trying to train again with -network_args "algo=locon" "dora_wd=True" now

@SlZeroth Did you succeed?
