### ISSUE TITLE
Support sd1.5?

### ISSUE THREAD

**Issue by zcdliuwei** [kohya-ss/sd-scripts#1132]
Thank you for your selfless contribution
May I ask if it is possible to train on SD1.5? I have a batch of text and image pairs from Midjourney, and I would like to use SD1.5 as the base model to train my own model instead of SDXL

**Comment by BootsofLagrangian** [comment]
You can train SD1.5 base models. 
1. peft methods can available on [train_network.py](https://github.com/kohya-ss/sd-scripts/blob/main/train_network.py)
2. full finetuning also can available on [fine_tune.py](https://github.com/kohya-ss/sd-scripts/blob/main/fine_tune.py)

**Comment by zcdliuwei** [comment]
> You can train SD1.5 base models.
> 
> 1. peft methods can available on [train_network.py](https://github.com/kohya-ss/sd-scripts/blob/main/train_network.py)
> 2. full finetuning also can available on [fine_tune.py](https://github.com/kohya-ss/sd-scripts/blob/main/fine_tune.py)

Thank you for your reply. I will give it a try right away
thanks again
