### ISSUE TITLE
Send to WandB: Training Model Name (as wandb run) and Set Project Name

### ISSUE THREAD

**Issue by rafstahelin** [kohya-ss/sd-scripts#1179]
Trying to send this to Wandb

1.  Use "training model name" as wandb "run name"
2.  Set wand "wandb Project name"
3.  Send training args to wandb

-----------
It used to work for me using the following code in Library > train_util.py:
`if args.wandb_api_key is not None:
                wandb.login(key=args.wandb_api_key)
                wandb.init(project="t1k0", name=args.output_name, config=args)`
However, this doesnt seem to be supported in the latest updates

----------
#792 seems to address this but refers to new workaround, using:
"Kohya is suggesting to move the config from wandb to the accelerator interface via init_kwargs/config as starting the wandb init outside the accelerator hook could cause side effects."
https://github.com/kohya-ss/sd-scripts/pull/792#issuecomment-1776507183

with:
`accelerator.init_trackers(
         project_name=args.output_name, 
         config=args
         init_kwargs={},
)`
and 
`accelerator.init_trackers(
         project_name=args.output_name, 
         config=args,
         init_kwargs={'wandb': args.wandb_init_args},
)`

----------------
Can anyone offer a working edit to the code? 

Even better, to add it to accelerator cli args?

**Comment by ashleykleynhans** [comment]
You should be able to just add it to accelerator cli args:

```
--log_tracker_name "finetuning" --wandb_run_name "myrun"
```

Where `log_tracker_name` is the project name, and `wandb_run_name` is the run name.

I haven't tested this though so not sure that it works, but looks like it should work by reading the code.

**Comment by rafstahelin** [comment]
> You should be able to just add it to accelerator cli args:
> 
> ```
> --log_tracker_name "finetuning" --wandb_run_name "myrun"
> ```
> 
> Where `log_tracker_name` is the project name, and `wandb_run_name` is the run name.
> 
> I haven't tested this though so not sure that it works, but looks like it should work by reading the code.

testing

**Comment by ashleykleynhans** [comment]
@rafstahelin I believe you can close this issue now that @bmaltais has implemented it in the GUI and you have confirmed that it is working.

**Comment by rafstahelin** [comment]
> @rafstahelin I believe you can close this issue now that @bmaltais has implemented it in the GUI and you have confirmed that it is working.

yea true

**Comment by rafstahelin** [comment]
thanks Bernard
