### ISSUE TITLE
How to unload Lora from sdxl to achieve dynamic switching of Lora?

### ISSUE THREAD

**Issue by tsogzark** [kohya-ss/sd-scripts#1185]
Are there any example codes available for uninstalling Lora? Similar to diffusers [unload_lora_weights](https://github.com/huggingface/diffusers/pull/4034/files#diff-c54108820590e5247c5a7bd1aa43b68d53a40bc630f0791cb537047752520fab)

**Comment by tsogzark** [comment]
> What script or inference environment do you use?
> 
> If you use `networks.lora.py` from another script, there are `backup_weights`, `pre_calculation` and `restore_weights` methods.

Thank you. It works.

**Comment by ljwdust** [comment]
Could you give an example? Thank you.
