### ISSUE TITLE
Support B-LoRA

### ISSUE THREAD

**Issue by sdbds** [kohya-ss/sd-scripts#1215]
Style and concept separation training

https://github.com/yardenfren1996/B-LoRA

**Comment by slashedstar** [comment]
This can be done with lycoris https://github.com/KohakuBlueleaf/LyCORIS/blob/main/docs/Preset.md
Set the config.toml file to
```enable_conv = false
unet_target_module = []
unet_target_name = ["output_blocks.0.1."]
text_encoder_target_module = ["CLIPAttention"]
text_encoder_target_name = []```
for content and output_blocks.1.1. for style

**Comment by slashedstar** [comment]
> Thanks for that, @slashedstar ! I'm definitely going to give it a try. My results with the B-Lora repo have been super promising, but I didn't realize it would be so simple to convert to a Lycoris config.
> 
> Have you tested the config and confirmed that the results match B-Lora's implementation?

I don't remember exactly, I think I converted the diffusers lora for running it with the webui and it matched the lycoris at least on containing only the correct up/out block, idk if the clip attention part is the same as theirs though, maybe they also train the CLIPMLP, but from this https://github.com/yardenfren1996/B-LoRA/blob/main/train_dreambooth_b-lora_sdxl.py#L73 I think they also train just the clip attention (I'm not good with the technicalities of SD)

**Comment by slashedstar** [comment]
I got it from https://github.com/KohakuBlueleaf/LyCORIS/blob/d2a7643e9406684190f4e28ad58adb7dc51ba59c/lycoris/kohya/sdxl_model_util.py#L271

hf_up_atn_prefix = f"up_blocks.{i}.attentions.{j}."
sd_up_atn_prefix = f"output_blocks.{3*i + j}.1."

output_blocks.{3*0 + 0}.1. = output_blocks.0.1.

**Comment by slashedstar** [comment]
[unet_map.txt](https://github.com/user-attachments/files/16038469/unet_map.txt)
I don't remember how I made this file, but it should contain all blocks and their respective names for lycoris / diffusers

**Comment by slashedstar** [comment]
Yeah, you should keep alpha = dim so you don't have to scale the learning rate when changing the dim

**Comment by slashedstar** [comment]
Its the same as training a regular lora, it just makes a smaller file, the prodigy_safeguard_warmup tends to makes it estimate a lower LR hence why it may train slower

**Comment by slashedstar** [comment]
Oh thats quite nice, thanks for testing and sharing the config!

**Comment by Specthram** [comment]
any chance to put the lora type in kohya_ss ?
