### ISSUE TITLE
AdamW8bit does not work in full finetune

### ISSUE THREAD

**Issue by rafstahelin** [kohya-ss/sd-scripts#1248]
#Tried using A100 guy but the process just runks amok. Does this mean AdamW8bit is dead for full fine tuning? 
#Why can't it run any more?

![image](https://github.com/kohya-ss/sd-scripts/assets/64715158/1ad4cfa2-6934-4ee3-a03d-7ba2411ab226)

Even @bmaltais says it's not running

**Comment by codesstar** [comment]
Hey, I don't think AdamW 8bit dosen't work. I try to finetune SDXL using 30w text-image pairs with the optimizer of AdamW 8bit. I did't find anything wrong.(Perhaps the gernerative quality is not so good, but I think it's good enough for me)

**Comment by rafstahelin** [comment]
> Hey, I don't think AdamW 8bit dosen't work. I try to finetune SDXL using 30w text-image pairs with the optimizer of AdamW 8bit. I did't find anything wrong.(Perhaps the gernerative quality is not so good, but I think it's good enough for me). I think what "AdamW 8bit dosen't seem to work" means is AdamW8bit dosen't perform well in the context of batch szie 1 under the limited 24GPU

Interesting, I will try it with lower batch size. I had it at bs6 and it didnt even give the OOO message

**Comment by laksjdjf** [comment]
This means that AdamW8bit would cause an out-of-memory error. Not about performance.

**Comment by rafstahelin** [comment]
Maybe need to try without xformers and use sep since Kohya is now running on Pytorch 2.0.1?

**Comment by rafstahelin** [comment]
@kohya-ss  Yea. But i was running with formers in latest kohya_ss 23.1.2

It was just not having it

But now I'm suddenly able to run adamW8bit on my 4090 using sdpa

Still need to check the quality. Any tips about running sdpa Cross attention? Seems promising

**Comment by rafstahelin** [comment]
So what about in A100 80gb


or ada6000 48gb?


What best results as I’m most likely going to train on runpod with
AdamW8bit batch size 6


thanks

best regards, raf
