### ISSUE TITLE
Training stuck at step zero

### ISSUE THREAD

**Issue by machineminded** [kohya-ss/sd-scripts#1276]
@bmaltais ,

I've successfully used kohya in the past, but for some reason I'm not able to get training to start with a fresh install.

I click "Start Training" but the progress bar is stuck at 0/xxxxx steps, and no GPU resources are being used at all.

Any tips?  I've tried destroying the venv and re-creating, but no dice.  I am using torch ` 2.2.2+cu118` instead of `2.1.2+cu118` but I wouldn't think that would matter.  I couldn't install `2.1.2+cu118` because it isn't found in the index.

**Comment by machineminded** [comment]
I should note that if caching latents is enabled, it hangs during that process as well.

**Comment by SarthakNikhal** [comment]
@machineminded Do you see cuda enabled when you use is_available()? Let me know how I can reproduce this issue

**Comment by machineminded** [comment]
I opened this in the wrong repo.  Sorry @SarthakNikhal
