### ISSUE TITLE
Fused optimizerでのresume

### ISSUE THREAD

**Issue by rena0408** [kohya-ss/sd-scripts#1344]
素晴らしい機能をありがとうございます。
Fused optimizerで--resumeした場合にresume元のstateと全く同一の画像が出力されてしまいます
tensorboardでは学習が進んでいるように見えるのですが…
Fused optimizerはresumeに対応していないのでしょうか？

**Comment by yushan777** [comment]
I can confirm.  resumed results seem to be pixel-identical to previous checkpoint.  

`--fused_backward_pass` mode seems to work really well though!

**Comment by rena0408** [comment]
Xも見てました！
SD3等も来てお忙しい所改善してくださって本当にありがとうございます！
