### ISSUE TITLE
Why do the trained LoRA models consistently have a size of 41MB, even when I adjust the number of steps?

### ISSUE THREAD

**Issue by tsogzark** [kohya-ss/sd-scripts#1352]
What factors influence the size of the lora model?

**Comment by DKnight54** [comment]
Number of steps do not affect the network size. The number of steps affects how much learning the model will has, ie, too little  steps, and the LoRA will not be able to reproduce the images, too much steps, and the LoRA will be overbaked. There is no hard or fast rule on how many steps are needed as there are a lot of possible factors, including the type of optimizers, the subject your are training on, the quality of the source images etc.

The size of the LoRA is impacted by the network size, ie: network_dim arguement. The larger, in theory, the more details you can store. However, this also impacts the VRAM required during training.
