### ISSUE TITLE
xformers calls for 0.0.14 when it doesn't exist anymore.

### ISSUE THREAD

**Issue by Desuka-art** [kohya-ss/sd-scripts#136]
It's gone. It's like it never existed.  I think people have been having trouble downloading xformers because of this. What version should be use now?

**Comment by Desuka-art** [comment]
But when I try to use it on pip, it says that the wheel isn’t supported on my platform, which is Windows. What do I do?

**Comment by GucciFlipFlops1917** [comment]
Even Python 3.9 is incompatible, so it's worth an update. The 1.2.1+cu113 version of torch is necessary alongside py3.10.
