### ISSUE TITLE
SD3 training error

### ISSUE THREAD

**Issue by paoloski97** [kohya-ss/sd-scripts#1389]
When I try to train SD3, it returns this error:

 ```
File "/kaggle/working/./sd-scripts/sd3_train.py", line 64, in train
    not args.train_text_encoder or not args.cache_text_encoder_outputs
AttributeError: 'Namespace' object has no attribute 'train_text_encoder'
```

**Comment by leonary** [comment]
Kohya forgot to comment out some code. In sd3_train.py, comment out lines 63-65

# assert (
# not args.train_text_encoder or not args.cache_text_encoder_outputs
# ), "cache_text_encoder_outputs is not supported when training text encoder / cache_text_encoder_outputs are supported even if you learn with text encoder"

@kohya-ss

**Comment by leonary** [comment]
> Sorry I fixed again. Not it should work.

Sorry to bother you, but could you please also check #1390 . I have observed the problem that SD3 cannot fit on larger datasets in all script projects (OneTrainer, Diffuser, SimpleTuner, SD-scripts). Do you have any idea about this? Is it a problem with the SD3 model itself, or are all the training methods currently used not suitable for SD3?
