### ISSUE TITLE
Unable to provide list-type arguments via Windows CLI

### ISSUE THREAD

**Issue by ThereforeGames** [kohya-ss/sd-scripts#1401]
Hi,

I launch your training scripts through Windows batch files as follows:

```bat
accelerate launch sdxl_train_network.py ^
--resolution="1024,1024" ^
--max_train_steps=3000 ^
[...]
```

This generally works fine, with the exception of arguments that are meant to take multiple key-value pairs as a list, such as `--optimizer_args` and `--lr_scheduler_args`. I have not found a way to successfully pass such arguments via Windows CLI.

Here's what I've tried:

```bat
--optimizer_args="weight_decay=1e-04 betas=(0.9,0.999) eps=1e-08"
```

```bat
--optimizer_args=["weight_decay=1e-04","betas=(0.9,0.999)","eps=1e-08"]
```

```bat
--optimizer_args="weight_decay=1e-04" "betas=(0.9,0.999)" "eps=1e-08"
```

All of those result in either "too many values to unpack" or "unrecognized argument" errors.

I still need to try the following approach, where I place each sub-arg on its own line:

```bat
--optimizer_args="weight_decay=1e-04" ^
--optimizer_args="betas=(0.9,0.999)" ^
--optimizer_args="eps=1e-08"
```

But I suspect this won't work either. Have I overlooked an obvious solution?

---

This issue has been reported previously ([example here](https://github.com/kohya-ss/sd-scripts/issues/814#issuecomment-1854267567)), but I don't think it was diagnosed as a Windows problem.

As a workaround, I have patched `train_util.py` (line 3851) to split a single string with spaces into the expected format:

```python
    if args.optimizer_args is not None and len(args.optimizer_args) > 0:
        # Check for presence of space, allows for Windows support
        if " " in args.optimizer_args[0]:
            opt_args = args.optimizer_args[0].split()
            opt_args_dict = {}
            for arg in opt_args:
                key, value = arg.split("=")
                opt_args_dict[key] = ast.literal_eval(value)

            args.optimizer_args = opt_args_dict
        else:
            for arg in args.optimizer_args:
                key, value = arg.split("=")
                value = ast.literal_eval(value)

                # value = value.split(",")
                # for i in range(len(value)):
                #     if value[i].lower() == "true" or value[i].lower() == "false":
                #         value[i] = value[i].lower() == "true"
                #     else:
                #         value[i] = ast.float(value[i])
                # if len(value) == 1:
                #     value = value[0]
                # else:
                #     value = tuple(value)

                optimizer_kwargs[key] = value
```

I would open a PR with these changes, but there's still room for improvement:

- My fix is hardcoded to `optimizer_args`; we probably need a generic function to support similar arguments.
- There is probably a smarter way to test for Windows-style values. I just checked for the presence of a space, which could have side effects.
- Not sure if it would cause problems downstream - will this solution affect the popular Kohya GUI?

Thanks.

**Comment by araleza** [comment]
I don't know if this will apply to Windows, but in my Linux command line, I pass the optimizer arguments without any quote decoration at all:

--optimizer_args scale_parameter=False relative_step=False warmup_init=False

Worth a try?
