### ISSUE TITLE
flux多卡训练的时候有问题

### ISSUE THREAD

**Issue by SongDI911** [kohya-ss/sd-scripts#1455]
accelerate launch  --mixed_precision bf16 --num_cpu_threads_per_process 8 --multi_gpu --num_processes=2 flux_train_network.py --pretrained_model_name_or_path flux1-dev.sft --clip_l /home/ubuntu/gxs/LLaMA_MODELS/sd3/text_encoders/clip_l.safetensors --t5xxl /home/ubuntu/gxs/LLaMA_MODELS/sd3/text_encoders/t5xxl_fp16.safetensors --ae /home/ubuntu/gxs/LLaMA_MODELS/flux/flux2/ae.safetensors --cache_latents_to_disk --save_model_as safetensors --sdpa --persistent_data_loader_workers --max_data_loader_n_workers 2 --seed 42 --gradient_checkpointing --mixed_precision bf16 --save_precision bf16 --network_module networks.lora_flux --network_dim 4 --optimizer_type adamw8bit --learning_rate 1e-4 --network_train_unet_only --cache_text_encoder_outputs --cache_text_encoder_outputs_to_disk --fp8_base --highvram --max_train_epochs 4 --save_every_n_epochs 1 --pretrained_model_name_or_path /home/ubuntu/gxs/LLaMA_MODELS/flux/flux2/flux1-dev.safetensors --output_dir /home/ubuntu/gxs/flux_lora/out_put --output_name flux-lora-L_logo --timestep_sampling sigmoid --train_data_dir /home/ubuntu/gxs/flux_lora/data --resolution "1024, 1024"  --model_prediction_type raw --guidance_scale 1.0 --loss_type l2 --cache_latents_to_disk --cache_text_encoder_outputs --cache_text_encoder_outputs_to_disk
这是我的训练参数
这是报错
ank1]:   File "/home/ubuntu/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/ubuntu/gxs/flux_lora/sd-scripts/library/flux_models.py", line 528, in forward
[rank1]:     return checkpoint(self._forward, *args, use_reentrant=False, **kwargs)
[rank1]:   File "/home/ubuntu/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/_compile.py", line 31, in inner
[rank1]:     return disable_fn(*args, **kwargs)
[rank1]:   File "/home/ubuntu/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
[rank1]:     return fn(*args, **kwargs)
[rank1]:   File "/home/ubuntu/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 488, in checkpoint
[rank1]:     ret = function(*args, **kwargs)
[rank1]:   File "/home/ubuntu/gxs/flux_lora/sd-scripts/library/flux_models.py", line 524, in _forward
[rank1]:     return self.out_layer(self.silu(self.in_layer(x)))
[rank1]:   File "/home/ubuntu/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/ubuntu/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/ubuntu/miniconda3/envs/flux_train/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 117, in forward
[rank1]:     return F.linear(input, self.weight, self.bias)
[rank1]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
W0815 17:24:44.806000 132518806837056 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 147202 closing signal SIGTERM
E0815 17:24:45.021000 132518806837056 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 1 (pid: 147203) of binary: /home/ubuntu/miniconda3/envs/flux_train/bin/python

**Comment by fireicewolf** [comment]
Maybe you need assign your gpu_id such as `accelerate launch --gpu_ids 0,1`(Sometimes some CPU integrated graphics maybe recognized as a GPU).
Or you can use` accelerate config` to make a config file, then use `accelerate launch --config pathtoyouerconfig.yaml` to launch your training session.

**Comment by SongDI911** [comment]
> Maybe you need assign your gpu_id such as `accelerate launch --gpu_ids 0,1`(Sometimes some CPU integrated graphics maybe recognized as a GPU). Or you can use` accelerate config` to make a config file, then use `accelerate launch --config pathtoyouerconfig.yaml` to launch your training session.

--gpu_ids 0,1 这个并没有实际解决问题

**Comment by fireicewolf** [comment]
You need to check your GPU id, may not `0,1`.
I recommend use `accelerate config` to make a config file, this config can be reused in your future works unless you change your hardware or upgrade accelerate make some api deprecated.

**Comment by kyrie111** [comment]
我和你遇到一样的问题，请问你最后解决了吗

**Comment by SongDI911** [comment]
> 我和你遇到一样的问题，请问你最后解决了吗

解决了
https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/flux_train_network.py#L383
修改return args.cache_text_encoder_outputs 为return False 避免text encoder被卸载
然后修改
https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/flux_train_network.py#L165
with accelerator.autocast():
                dataset.new_cache_text_encoder_outputs(text_encoders, accelerator.is_main_process)
为
with accelerator.autocast():
                dataset.new_cache_text_encoder_outputs(text_encoders, True)

**Comment by kyrie111** [comment]
> > 我和你遇到一样的问题，请问你最后解决了吗
> 
> 解决了
> 
> https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/flux_train_network.py#L383
> 
> 
> 修改return args.cache_text_encoder_outputs 为return False 避免text encoder被卸载
> 然后修改
> https://github.com/kohya-ss/sd-scripts/blob/c62c95e8626bdb727cedc8f037c82ab3a8e66059/flux_train_network.py#L165
> 
> 
> with accelerator.autocast():
> dataset.new_cache_text_encoder_outputs(text_encoders, accelerator.is_main_process)
> 为
> with accelerator.autocast():
> dataset.new_cache_text_encoder_outputs(text_encoders, True)

谢谢！解决了我的问题~
