### ISSUE TITLE
can flux_train_network.py trian a dreamboth_lora?

### ISSUE THREAD

**Issue by JoshonSmith** [kohya-ss/sd-scripts#1463]
can flux_train_network.py trian a dreamboth_lora?

I want to train a sks dog by using FLUX

**Comment by TheLastBen** [comment]
small tokens work just as good as with the sd models.

@kohya-ss any insight how to make this work on ComfyUI, the lora is trained using your library (not flux) but for flux :

lora key not loaded: lora_unet_context_embedder_.alpha
lora key not loaded: lora_unet_context_embedder_.lora_down.weight
lora key not loaded: lora_unet_context_embedder_.lora_up.weight
lora key not loaded: lora_unet_norm_out_linear_.alpha
lora key not loaded: lora_unet_norm_out_linear_.lora_down.weight
lora key not loaded: lora_unet_norm_out_linear_.lora_up.weight
lora key not loaded: lora_unet_proj_out_.alpha
lora key not loaded: lora_unet_proj_out_.lora_down.weight
lora key not loaded: lora_unet_proj_out_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_attn_to_k_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_0_attn_to_k_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_attn_to_k_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_attn_to_q_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_0_attn_to_q_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_attn_to_q_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_attn_to_v_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_0_attn_to_v_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_attn_to_v_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_norm_linear_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_0_norm_linear_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_norm_linear_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_proj_mlp_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_0_proj_mlp_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_proj_mlp_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_proj_out_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_0_proj_out_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_0_proj_out_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_attn_to_k_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_10_attn_to_k_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_attn_to_k_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_attn_to_q_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_10_attn_to_q_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_attn_to_q_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_attn_to_v_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_10_attn_to_v_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_attn_to_v_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_norm_linear_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_10_norm_linear_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_norm_linear_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_proj_mlp_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_10_proj_mlp_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_proj_mlp_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_proj_out_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_10_proj_out_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_10_proj_out_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_attn_to_k_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_11_attn_to_k_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_attn_to_k_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_attn_to_q_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_11_attn_to_q_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_attn_to_q_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_attn_to_v_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_11_attn_to_v_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_attn_to_v_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_norm_linear_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_11_norm_linear_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_norm_linear_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_proj_mlp_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_11_proj_mlp_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_proj_mlp_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_proj_out_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_11_proj_out_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_11_proj_out_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_12_attn_to_k_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_12_attn_to_k_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_12_attn_to_k_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_12_attn_to_q_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_12_attn_to_q_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_12_attn_to_q_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_12_attn_to_v_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_12_attn_to_v_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_12_attn_to_v_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_12_norm_linear_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_12_norm_linear_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_12_norm_linear_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_18_proj_mlp_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_18_proj_out_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_18_proj_out_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_18_proj_out_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_19_attn_to_k_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_19_attn_to_k_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_19_attn_to_k_.lora_up.weight
lora key not loaded: lora_unet_single_transformer_blocks_19_attn_to_q_.alpha
lora key not loaded: lora_unet_single_transformer_blocks_19_attn_to_q_.lora_down.weight
lora key not loaded: lora_unet_single_transformer_blocks_19_attn_to_q_.lora_up.weight
.
.
.
.
lora key not loaded: lora_unet_x_embedder_.alpha
lora key not loaded: lora_unet_x_embedder_.lora_down.weight
lora key not loaded: lora_unet_x_embedder_.lora_up.weight

**Comment by MaxThunderscore** [comment]
Training a flux lora with a trigger like `sks dog` will work just fine, although it's not necessary.
