### ISSUE TITLE
Trying to merge Flux Loras

### ISSUE THREAD

**Issue by VadimFedenko** [kohya-ss/sd-scripts#1522]
I'm using
`networks/flux_merge_lora.py --concat --save_to ./lora_weight/please.safetensors --models ./lora_weight/ANTIBLUR2.safetensors ./lora_weight/ANTIBLUR4.safetensors --ratios 0.3 0.7 --save_precision fp16 --loading_device cuda --working_device cpu `

but getting this as result
```
                    INFO     loading: ./lora_weight/ANTIBLUR2.safetensors                                                                                                                flux_merge_lora.py:394
                    INFO     dim: [], alpha: []                                                                                                                                          flux_merge_lora.py:425
                    INFO     merging...                                                                                                                                                  flux_merge_lora.py:428
  0%|                                                                                                                                                                                 | 0/988 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\AI\sd-scripts-sd3\networks\flux_merge_lora.py", line 657, in <module>
    merge(args)
  File "D:\AI\sd-scripts-sd3\networks\flux_merge_lora.py", line 553, in merge
    state_dict, metadata = merge_lora_models(args.models, args.ratios, merge_dtype, args.concat, args.shuffle)
  File "D:\AI\sd-scripts-sd3\networks\flux_merge_lora.py", line 442, in merge_lora_models
    base_alpha = base_alphas[lora_module_name]
KeyError: 'transformer.single_transformer_blocks.0.attn.to_k'
```

any tips on how to get it working?

**Comment by tianainanetapsys** [comment]
have the same error

**Comment by VadimFedenko** [comment]
people also got the same error in reddit https://www.reddit.com/r/StableDiffusion/comments/1f2k0fk/comment/lkkkqx5/?context=3

**Comment by VadimFedenko** [comment]
yes, you're correct. tried to merge LoRa from ai-toolkit.
Will be patiently waiting for its support

**Comment by Jonseed** [comment]
A workaround for merging AI-Toolkit LoRAs for now is to merge them both into a Flux1.dev checkpoint (with `--diffusers` option), and then use the flux_extract_lora.py to extract them back out as one LoRA. That seems to be working. I would re-open this issue though, as direct merging of AI-Toolkit models would be a great addition (as well as a direct merging of a mix of sd-scripts and AI-Toolkit LoRAs). I think the only direct merging together of LoRAs right now that works is sd-scripts type LoRAs.

**Comment by SonaliGodavarthy** [comment]
To merge AI-toolkit LoRAs you can use sd-scripts convert_flux.lora.py from ai-toolkit to sd-script format LoRAs. and then use flux_merge_lora.py to merge them
