### ISSUE TITLE
VAE error with FLUX finetuning

### ISSUE THREAD

**Issue by adeysif** [kohya-ss/sd-scripts#1535]
Getting this error when I try to start a finetune training
Happens when I try with the Full Flux Dev as well, what am I doing wrong? Am I using the wrong base model somehow?

`2024-08-30 12:28:38 INFO     found 1692 images.                                            prepare_buckets_latents.py:73
                    INFO     loading existing metadata: meta_cap.json                      prepare_buckets_latents.py:76
                    INFO     load VAE: F:/fok/AGAIN/ComfyUI/models/unet/flux1-dev-fp8.safetensors     model_util.py:1268
Traceback (most recent call last):
  File "Z:\kohya_ss-sd3-flux.1\sd-scripts\finetune\prepare_buckets_latents.py", line 286, in <module>
    main(args)
  File "Z:\kohya_ss-sd3-flux.1\sd-scripts\finetune\prepare_buckets_latents.py", line 89, in main
    vae = model_util.load_vae(args.model_name_or_path, weight_dtype)
  File "Z:\kohya_ss-sd3-flux.1\sd-scripts\library\model_util.py", line 1304, in load_vae
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(vae_sd, vae_config)
  File "Z:\kohya_ss-sd3-flux.1\sd-scripts\library\model_util.py", line 415, in convert_ldm_vae_checkpoint
    new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"]
KeyError: 'encoder.conv_in.weight'`

I also get this error later before it stops

`2024-08-30 12:28:46 INFO     Loading settings from                                                    train_util.py:4189
                             Z:/F/kohya_ss/dataset/model/config_finetune-20240830-122839.toml...
                    INFO     Z:/F/kohya_ss/dataset/model/config_finetune-20240830-122839              train_util.py:4208
2024-08-30 12:28:46 INFO     Training with captions.                                                   flux_train.py:112
Traceback (most recent call last):
  File "Z:\kohya_ss-sd3-flux.1\sd-scripts\flux_train.py", line 905, in <module>
    train(args)
  File "Z:\kohya_ss-sd3-flux.1\sd-scripts\flux_train.py", line 127, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "Z:\kohya_ss-sd3-flux.1\sd-scripts\library\config_util.py", line 485, in generate_dataset_group_by_blueprint
    dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
  File "Z:\kohya_ss-sd3-flux.1\sd-scripts\library\train_util.py", line 1912, in __init__
    raise ValueError(f"no metadata / メタデータファイルがありません: {subset.metadata_file}")
ValueError: no metadata / メタデータファイルがありません: /meta_lat.json
Traceback (most recent call last):
  File "c:\users\adey\appdata\local\programs\python\python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\adey\appdata\local\programs\python\python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "Z:\kohya_ss-sd3-flux.1\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "Z:\kohya_ss-sd3-flux.1\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "Z:\kohya_ss-sd3-flux.1\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "Z:\kohya_ss-sd3-flux.1\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['Z:\\kohya_ss-sd3-flux.1\\venv\\Scripts\\python.exe', 'Z:/kohya_ss-sd3-flux.1/sd-scripts/flux_train.py', '--config_file', 'Z:/F/kohya_ss/dataset/model/config_finetune-20240830-122839.toml']' returned non-zero exit status 1.`

![image](https://github.com/user-attachments/assets/e30119f8-ae36-483c-a457-b03abbf1f2dc)

**Comment by BenDes21** [comment]
> Getting this error when I try to start a finetune training Happens when I try with the Full Flux Dev as well, what am I doing wrong? Am I using the wrong base model somehow?
> 
> `2024-08-30 12:28:38 INFO found 1692 images. prepare_buckets_latents.py:73 INFO loading existing metadata: meta_cap.json prepare_buckets_latents.py:76 INFO load VAE: F:/fok/AGAIN/ComfyUI/models/unet/flux1-dev-fp8.safetensors model_util.py:1268 Traceback (most recent call last): File "Z:\kohya_ss-sd3-flux.1\sd-scripts\finetune\prepare_buckets_latents.py", line 286, in <module> main(args) File "Z:\kohya_ss-sd3-flux.1\sd-scripts\finetune\prepare_buckets_latents.py", line 89, in main vae = model_util.load_vae(args.model_name_or_path, weight_dtype) File "Z:\kohya_ss-sd3-flux.1\sd-scripts\library\model_util.py", line 1304, in load_vae converted_vae_checkpoint = convert_ldm_vae_checkpoint(vae_sd, vae_config) File "Z:\kohya_ss-sd3-flux.1\sd-scripts\library\model_util.py", line 415, in convert_ldm_vae_checkpoint new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"] KeyError: 'encoder.conv_in.weight'`
> 
> I also get this error later before it stops
> 
> `2024-08-30 12:28:46 INFO Loading settings from train_util.py:4189 Z:/F/kohya_ss/dataset/model/config_finetune-20240830-122839.toml... INFO Z:/F/kohya_ss/dataset/model/config_finetune-20240830-122839 train_util.py:4208 2024-08-30 12:28:46 INFO Training with captions. flux_train.py:112 Traceback (most recent call last): File "Z:\kohya_ss-sd3-flux.1\sd-scripts\flux_train.py", line 905, in <module> train(args) File "Z:\kohya_ss-sd3-flux.1\sd-scripts\flux_train.py", line 127, in train train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group) File "Z:\kohya_ss-sd3-flux.1\sd-scripts\library\config_util.py", line 485, in generate_dataset_group_by_blueprint dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params)) File "Z:\kohya_ss-sd3-flux.1\sd-scripts\library\train_util.py", line 1912, in __init__ raise ValueError(f"no metadata / メタデータファイルがありません: {subset.metadata_file}") ValueError: no metadata / メタデータファイルがありません: /meta_lat.json Traceback (most recent call last): File "c:\users\adey\appdata\local\programs\python\python310\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\users\adey\appdata\local\programs\python\python310\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "Z:\kohya_ss-sd3-flux.1\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module> File "Z:\kohya_ss-sd3-flux.1\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main args.func(args) File "Z:\kohya_ss-sd3-flux.1\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command simple_launcher(args) File "Z:\kohya_ss-sd3-flux.1\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) subprocess.CalledProcessError: Command '['Z:\\kohya_ss-sd3-flux.1\\venv\\Scripts\\python.exe', 'Z:/kohya_ss-sd3-flux.1/sd-scripts/flux_train.py', '--config_file', 'Z:/F/kohya_ss/dataset/model/config_finetune-20240830-122839.toml']' returned non-zero exit status 1.`
> 
> ![image](https://private-user-images.githubusercontent.com/9382953/363264197-e30119f8-ae36-483c-a457-b03abbf1f2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTM3MDAsIm5iZiI6MTcyNTExMzQwMCwicGF0aCI6Ii85MzgyOTUzLzM2MzI2NDE5Ny1lMzAxMTlmOC1hZTM2LTQ4M2MtYTQ1Ny1iMDNhYmJmMWYyZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzFUMTQxMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2MyNzJjOGExN2MxOGUzZTU4YzQ0ZDBmMjYyYTIyOWI2NGY3YzVjNDllZDI0ZjJkNDAyYWJkOGY1NmVlNThmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t81-gI-fpX9mQSrv97BIpTN5daWm83uLZzekQxF39Yg)

Hi, did you successfully generate the meta_lat.json for a flux fine tuning ? If yes which path did you set for the model argument ? I tried to set the dev checkpoint but its not working

**Comment by adeysif** [comment]
Yeah you need a toml dataset config file for full finetuning - read somewhere that the bucketing script doesn't work for flux
