### ISSUE TITLE
Block swapping documentation?

### ISSUE THREAD

**Issue by peteallen** [kohya-ss/sd-scripts#1547]
Is there anywhere I can read about the concept behind the --double_blocks_to_swap and --single_blocks_to_swap options? I've searched here and on Google and haven't found much info, and I don't understand what these options do.

**Comment by setothegreat** [comment]
The readme doesn't really explain what the "swap" part of block swapping actually is, or why it would be helpful or not. Does it swap the weights between a given pair of blocks before training, does it unload and reload a random set of blocks over the course of training to reduce memory usage, or does it do something else entirely?

**Comment by peteallen** [comment]
Looking through the code, it appears to be swapping blocks between the GPU and CPU to conserve VRAM. My testing has been a little inconsistent but in general, higher numbers seem to lead to lower VRAM usage. 

I’m not sure the difference between double and single blocks, though.

**Comment by AdAstra-93** [comment]
> Looking through the code, it appears to be swapping blocks between the GPU and CPU to conserve VRAM. My testing has been a little inconsistent but in general, higher numbers seem to lead to lower VRAM usage.
> 
> I’m not sure the difference between double and single blocks, though.
> […](#)

@peteallen can I prevent this behavior if I have enough VRAM? I want faster trainings
