### ISSUE TITLE
FLUX LoRA training getting terminated without any error - 64 GB RAM - video shared

### ISSUE THREAD

**Issue by FurkanGozukara** [kohya-ss/sd-scripts#1556]
@kohya-ss any ideas?

Latest version 

Here video of what happens

https://github.com/user-attachments/assets/07adcb73-32fb-40c9-8745-e064d910e4c7

The user has 64 GB RAM, also set virtual RAM to 50 GB

tested after restarting computer, reinstalling again too

Here what happens on CMD tested with --debug

How can we find the reason?

Accelerate is set as shown in this video : https://youtu.be/adVhm9aI9Gc

![1](https://github.com/user-attachments/assets/5f5bdc8e-0058-436b-bc2e-ca039dc7ae27)

![2](https://github.com/user-attachments/assets/c35c3df2-4515-40a9-b541-1e8eeb2267bb)

**Comment by FurkanGozukara** [comment]
> The log says `accelerator device: cpu`, so all models run on CPU. Please retry `accelerat config`.

he says he did very weird. i will tell him again

**Comment by dalmackay** [comment]
@FurkanGozukara  Your v24 configs are doing this

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara Your v24 configs are doing this

v24 config can't do this because config doesn't have anything related to it. copy paste your training cmd here and we will see your accelerator using cpu

I also opened an issue thread on bmaltais : https://github.com/bmaltais/kohya_ss/issues/2775

if you message me from discord i can connect your pc and check out

**Comment by FurkanGozukara** [comment]
@dalmackay here just got a reply from another supporter

![image](https://github.com/user-attachments/assets/facfb614-e94d-426f-a29f-757849c08592)

**Comment by dalmackay** [comment]
> > @FurkanGozukara Your v24 configs are doing this
> 
> v24 config can't do this because config doesn't have anything related to it. copy paste your training cmd here and we will see your accelerator using cpu
> 
> I also opened an issue thread on bmaltais : [bmaltais/kohya_ss#2775](https://github.com/bmaltais/kohya_ss/issues/2775)
> 
> if you message me from discord i can connect your pc and check out

meant that it is happening to everyone only after upgrading to v24. 
https://pastebin.com/BzdL0eSq  Where do we see accelerator using cpu?
Accelerate was reconfigured, 3 times now. Entire PC crashes on caching_latents (blue screen, forced system restart).

**Comment by FurkanGozukara** [comment]
> > > @FurkanGozukara Your v24 configs are doing this
> > 
> > 
> > v24 config can't do this because config doesn't have anything related to it. copy paste your training cmd here and we will see your accelerator using cpu
> > I also opened an issue thread on bmaltais : [bmaltais/kohya_ss#2775](https://github.com/bmaltais/kohya_ss/issues/2775)
> > if you message me from discord i can connect your pc and check out
> 
> meant that it is happening to everyone only after upgrading to v24. https://pastebin.com/BzdL0eSq Where do we see accelerator using cpu? Accelerate was reconfigured, 3 times now. Entire PC crashes on caching_latents (blue screen, forced system restart).

I just made update please download v25 and let me know. i think i found the bug

**Comment by dalmackay** [comment]
> 
> I just made update please download v25 and let me know. i think i found the bug

@FurkanGozukara 

Works now but speed is very slow on Rank 4 config. 11+ s/it. default settings.



![Screenshot 2024-09-03 064900](https://github.com/user-attachments/assets/f910989b-262a-4690-a989-57bed586518d)

**Comment by FurkanGozukara** [comment]
> > I just made update please download v25 and let me know. i think i found the bug
> 
> @FurkanGozukara
> 
> Works now but speed is very slow on Rank 4 config. 11+ s/it. default settings.
> 
> ![Screenshot 2024-09-03 064900](https://private-user-images.githubusercontent.com/112755662/364011251-f910989b-262a-4690-a989-57bed586518d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzMzNzQsIm5iZiI6MTcyNTM3MzA3NCwicGF0aCI6Ii8xMTI3NTU2NjIvMzY0MDExMjUxLWY5MTA5ODliLTI2MmEtNDY5MC1hOTg5LTU3YmVkNTg2NTE4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxNDE3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTBmYWNmYWQwNjE2NmJlYjk2MWRlMmVjNmRjYmFjOWMyZGE5M2U5YjMxNTU3ZGNkMzI1ZjI2NDViNDJlY2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FO7-PU2v_vUxwc2E327DwQS3HqwkZu-pTtGgaLhpdBI)

upgrade torch 2.5 use Install_Torch_2_5_Dev_Huge_Speed_Up.bat 

it will hugely speed up to like 5 - 5.5 second - also wait like 100 steps to get accurate speed do a fresh re-config on Rank_4_17250MB_4_85_Second_IT.json

because it looks like you are using split training

**Comment by dalmackay** [comment]
> upgrade torch 2.5 use Install_Torch_2_5_Dev_Huge_Speed_Up.bat
> 
> it will hugely speed up to like 5 - 5.5 second - also wait like 100 steps to get accurate speed do a fresh re-config on Rank_4_17250MB_4_85_Second_IT.json
> 
> because it looks like you are using split training

Am already on 2.5 dev.
Waited til 100 steps and still 11.4 s/it

This is your v25 config still zipped. split mode true


![Screenshot 2024-09-03 072517](https://github.com/user-attachments/assets/a23783d5-94b0-42d6-848f-5bde6d1ac13e)

**Comment by FurkanGozukara** [comment]
> > upgrade torch 2.5 use Install_Torch_2_5_Dev_Huge_Speed_Up.bat
> > it will hugely speed up to like 5 - 5.5 second - also wait like 100 steps to get accurate speed do a fresh re-config on Rank_4_17250MB_4_85_Second_IT.json
> > because it looks like you are using split training
> 
> Am already on 2.5 dev. Waited til 100 steps and still 11.4 s/it
> 
> This is your v25 config still zipped. split mode true
> 
> ![Screenshot 2024-09-03 072517](https://private-user-images.githubusercontent.com/112755662/364024477-a23783d5-94b0-42d6-848f-5bde6d1ac13e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzQwMjksIm5iZiI6MTcyNTM3MzcyOSwicGF0aCI6Ii8xMTI3NTU2NjIvMzY0MDI0NDc3LWEyMzc4M2Q1LTk0YjAtNDJkNi04NDhmLTViZGU2ZDFhYzEzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxNDI4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOThmYTRjZGU4Nzg2NzMyODI0NDAxZmYzOWVhZjA4NzJmZTQ1OGU4MzcyMjM1NjEyOGRlNTkwZGIwNzEzNjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5P1MDIS33UsgLQEtR1zRPZD8J7kdhXOHwxVrk2dlKbs)

wow i made a big mistake fixing
