### ISSUE TITLE
Cannot Start training with Lora.

### ISSUE THREAD

**Issue by Kwijiboe** [kohya-ss/sd-scripts#156]
My Python version is 3.10.6 according to powershell. 
I'm on ASUS NVIDIA GeForce GTX 1070 8GB GDDR5.

![ERROR](https://user-images.githubusercontent.com/103762215/216849864-7ef79c7d-a5a7-4ddc-b6d9-c63e4c876975.png)

**Comment by einsflash** [comment]
I have same problem, how do you solve it？
