### ISSUE TITLE
FLUX LoRA Extraction Resemblance Issue

### ISSUE THREAD

**Issue by FurkanGozukara** [kohya-ss/sd-scripts#1610]
I have used below config to extract 128 LoRA Network Rank with 0.99 Clamp Quantile and results are really bad

What does Clamp Quantile do @kohya-ss ?

Then I tried 0.01 Clamp Quantile and it is all noise :)

Here what i mean

left one is fine tuned model, right one is extracted 128 Rank FLUX LoRA

tested on SwarmUI latest which works perfect on both fine tuned checkpoints and trained LoRAs

![image](https://github.com/user-attachments/assets/6960db11-f058-4b49-a368-92a98afc1f9c)

Config

![image](https://github.com/user-attachments/assets/41204b51-7655-4d10-82ef-45a54975b4fb)

**Comment by FurkanGozukara** [comment]
ok it was related to clamp quantile :D

**Comment by woct0rdho** [comment]
Hi @FurkanGozukara , could you try to set the quantile to 1 and see if the result is closer to the original model?

Recently I found that clamping to 99% quantile indeed causes quality loss, see https://github.com/Stability-AI/stability-ComfyUI-nodes/issues/11 . Some recent issues about Flux Krea LoRA may also be related to this, and I'd like to collect more failure cases.

**Comment by woct0rdho** [comment]
@kohya-ss I've seen this 'clamp to 99% quantile' appearing in many places. Do you have any idea who originally proposed this?

**Comment by FurkanGozukara** [comment]
> Hi [@FurkanGozukara](https://github.com/FurkanGozukara) , could you try to set the quantile to 1 and see if the result is closer to the original model?
> 
> Recently I found that clamping to 99% quantile indeed causes quality loss, see [Stability-AI/stability-ComfyUI-nodes#11](https://github.com/Stability-AI/stability-ComfyUI-nodes/issues/11) . Some recent issues about Flux Krea LoRA may also be related to this, and I'd like to collect more failure cases.

true i posted this as setting as 1 is the best and highest rank also yields best results

highest network lora rank of course makes it bigger size but otherwise resemblance is off 

i feel something is wrong

**Comment by kohya-ss** [comment]
> [@kohya-ss](https://github.com/kohya-ss) I've seen this 'clamp to 99% quantile' appearing in many places. Do you have any idea who originally proposed this?

I think this was first proposed by Kblueleaf. The page for the first implementation seems to have been deleted, but there is a discussion in the PR below: 
https://github.com/kohya-ss/sd-scripts/pull/243
