### ISSUE TITLE
FLUX: Bleeding? 

### ISSUE THREAD

**Issue by DarkAlchy** [kohya-ss/sd-scripts#1633]
Been mentioned that is one of Flux's greatest downfalls, but I wonder where it comes from (and how to fix it)?  In my training I train one style I demand works for the entire image (as it did on every other model I have trained on) but all Flux trainings in realism seem to be of the subject only and the background is intermixed.  For instance, I train medieval style then generate an image to see medieval intermixed with modern people and things.  I guess that is a subset of the bleeding issue?  Not sure, but I hope we can actually train this model locally via some block scheme, etc...

Have any ideas about a single concept/style not working for everything in the generated image(s)?

**Comment by kopyl** [comment]
I'm experiencing this as well.

I'm wondering if training multi-subject can fix it partially.

Also maybe it's a good idea to train a model which would be responsible for detecting whether a model's generated noise residual leads to bleeding.
If it is, then we increase the loss in the training process.

**Comment by DarkAlchy** [comment]
Multi concepts is where this was first found, and is a PITA to try and train.

**Comment by kopyl** [comment]
@DarkAlchy i even have it in a single-concept

**Comment by DarkAlchy** [comment]
@kopyl Yes, I find it in regular gens.  Flux has some issues.

**Comment by kopyl** [comment]
@DarkAlchy me too :(
