### ISSUE TITLE
Flux De-distilled Training Samples Garbled

### ISSUE THREAD

**Issue by kmacmcfarlane** [kohya-ss/sd-scripts#1703]
Should I expect sample prompts for de-distilled flux models to be working yet?

On the `sd3` branch, when finetuning a de-distilled model ([nyanko7/flux-dev-de-distill](https://huggingface.co/nyanko7/flux-dev-de-distill)) the sample image output does not seem to be working correctly. Inference output from the training checkpoints in ComfyUI look correct when applying CFG.

Example `prompt.toml`
```
[prompt]
#negative_prompt = "makeup, nude, naked, border, frame, signature, text, watermark"
width = 1024
height = 1024
scale = 1
sample_steps = 60
seed = 420

[[prompt.subset]]
prompt = "my cool prompt here"
```

I also tried with `scale` set to `3.0` thinking the inference code might need the guidance scale set higher for de-distilled inference. That resulted in the same issue.

**Comment by Ice-YY** [comment]
I've been training a LoRA model on a dataset with several art styles, each with its own unique trigger word. When I training on the base model, the LoRA outputs doesn’t change much regardless of which trigger word I use for the different art styles. However, when I train the LoRA model using the de-distilled base model, it does show some ability to differentiate between the trigger words, although the results are much worse compared to training LoRA on SDXL. At the moment, I'm experimenting with a larger (like 4.0) guidance scales to see if I can improve the results.
