### ISSUE TITLE
Cannot apply trained SD 3.5 LoRA in Diffusers

### ISSUE THREAD

**Issue by YujiaKCL** [kohya-ss/sd-scripts#1743]
Thanks for supporting the training for SD 3.5 family. The validation images during training seem to be good. 
After the LoRA weights are ready, I found it does not work in diffusers StableDiffusion3Pipeline. My diffusers version is 0.31.0.
No warnings or errors, but no LoRA effects. 

Can you please let me know how to make the LoRAs work in diffusers?
Thank you.

**Comment by JoshonSmith** [comment]
should convert to diffusers format？

**Comment by YujiaKCL** [comment]
Thanks. Diffusers supports FLUX.1 LoRA quite well. It can be a nice feature if this repo can work with diffusers' infer.
