### ISSUE TITLE
How the lora weight be trained in the train_network.py ?

### ISSUE THREAD

**Issue by phyllispeng123** [kohya-ss/sd-scripts#1833]
I wonder in the `train_network.py`, how the network (lora) weight is used in training? When I am tracing the code, I find the network is not used in `def get_noise_pred_and_target` in `flux_train_network.py,`  the model_pred only include the original Flux model. Can somebody help me explain how the network weight is trained?

`model_pred = unet(
                    img=img, 
                    img_ids=img_ids,
                    txt=t5_out,
                    txt_ids=txt_ids,
                    y=l_pooled,
                    timesteps=timesteps / 1000,
                    guidance=guidance_vec,
                    txt_attention_mask=t5_attn_mask )`

**Comment by rockerBOO** [comment]
the model is augmented with the LoRA weights and the original weights are frozen. So it will look similar to the full model but have it setup to train only the LoRA
