### ISSUE TITLE
Trying to use Dadaptation

### ISSUE THREAD

**Issue by thojmr** [kohya-ss/sd-scripts#220]
Trying to use the new Dadaptation optimizer but it fails here.  The only values availaable for `lr_scheduler.optimizers[0].param_groups[0]`  when using `--optimizer_type "DAdaptation"` are:

- lr
- betas
- eps
- weight_decay
- initial_lr
- params

Where does 'd' come from?

```
Traceback (most recent call last):
  File "/root/data/fine_tune.py", line 353, in <module>
    train(args)
  File "/root/data/fine_tune.py", line 297, in train
    logs["lr/d*lr"] = lr_scheduler.optimizers[0].param_groups[0]['d']*lr_scheduler.optimizers[0].param_groups[0]['lr']
KeyError: 'd'
```

**Comment by thojmr** [comment]
Ah, sill had `--use_8bit_adam` stuck in there.  Should probably assert that this flag is not used in conjunction with Dadaptation

**Comment by BootsofLagrangian** [comment]
'd' is a D in "Dadaptaion".

This 'd' means a distance-like value toward optimal minimum. more details in [paper](https://github.com/facebookresearch/dadaptation).

Unlike other optimizer, dadaptation use d*lr value as a learning rate.
