### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by Eaglewant** [kohya-ss/sd-scripts#228]
I only successfully trained once(AdamW,xformers,ban 8bit) and next time i want train but that not work 

I upgrade train_util.py  but that will show up another error

also upgrade many times 

GPU:RTX 2070 8G

VRAM:32G 

CPU:AMD Ryzen 7 3700X 8-core Processor

WINDOWS10

> caching latents.
> 100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:04<00:00,  6.06it/s]
> import network module: networks.lora
> create LoRA for Text Encoder: 72 modules.
> create LoRA for U-Net: 192 modules.
> enable LoRA for text encoder
> enable LoRA for U-Net
> prepare optimizer, data loader etc.
> use AdamW optimizer | {}
> running training / 学習開始
>   num train images * repeats / 学習画像の数×繰り返し回数: 2250
>   num reg images / 正則化画像の数: 0
>   num batches per epoch / 1epochのバッチ数: 2250
>   num epochs / epoch数: 1
>   batch size per device / バッチサイズ: 1
>   total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
>   gradient accumulation steps / 勾配を合計するステップ数 = 1
>   total optimization steps / 学習ステップ数: 2250
> steps:   0%|                                                                                  | 0/2250 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "E:\Aitraning\kohya_ss\train_network.py", line 507, in <module>
>     train(args)
>   File "E:\Aitraning\kohya_ss\train_network.py", line 329, in train
>     accelerator.init_trackers("network_train")
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 466, in wrapper
>     return func(self, *args, **kwargs)
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 1535, in init_trackers
>     tracker_init(project_name, self.logging_dir, **init_kwargs.get(str(tracker), {}))
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\accelerate\tracking.py", line 153, in __init__
>     self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 246, in __init__
>     self._get_file_writer()
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 276, in _get_file_writer
>     self.file_writer = FileWriter(
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 75, in __init__
>     self.event_writer = EventFileWriter(
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
>     tf.io.gfile.makedirs(logdir)
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 511, in recursive_create_dir_v2
>     _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
> tensorflow.python.framework.errors_impl.PermissionDeniedError: Failed to create a directory: C:/Users/ohmni; Permission denied
> steps:   0%|                                                                                  | 0/2250 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "E:\Aitraning\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
>     args.func(args)
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
>     simple_launcher(args)
>   File "E:\Aitraning\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['E:\\Aitraning\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=E:/modle/abyssl_counterfeit_pastelmix.safetensors', '--train_data_dir=E:/traning', '--resolution=512,512', '--output_dir=E:/AI/model', '--logging_dir=C:/Users/ohmni/AI/SAMPLE IMAGES/ADAMS/LORA OUTPUT/log', '--network_alpha=120', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=120', '--output_name=REGITION', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=2250', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=123433', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers']' returned non-zero exit status 1.
> 
> 
>

**Comment by GeoTronZ** [comment]
same prob did u fix it?

**Comment by zwxiang** [comment]
same prob did u fix it?

**Comment by Vektor369** [comment]
Same.
