### ISSUE TITLE
Unable to use kohya_ss even upgrade train_util.py

### ISSUE THREAD

**Issue by hungphongnhi** [kohya-ss/sd-scripts#231]
Hi, this is my first time training with LoRa, but it keeps traceback

At first, I got an error like the one below
https://github.com/kohya-ss/sd-scripts/issues/204
I upgrade train_util.py but that will show up another error
also, upgrade many times

GPU:RTX 2060 6G

Use DreamBooth method.
prepare train images.
found directory 100_Kaze style contains 79 image files
7900 train images with repeating.
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 79/79 [00:00<00:00, 120.49it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 7900
mean ar error (without repeats): 0.0
prepare accelerator
Using accelerator 0.15.0 or above.
load Diffusers pretrained models
text_encoder\model.safetensors not found
Fetching 16 files: 100%|█████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 8019.70it/s]
K:\D\Kohya\kohya_ss\venv\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Replace CrossAttention.forward to use xformers
caching latents.
100%|██████████████████████████████████████████████████████████████████████████████████| 79/79 [00:36<00:00,  2.14it/s]
import network module: networks.lora
create LoRA for Text Encoder: 138 modules.
create LoRA for U-Net: 192 modules.
load network weights from: K:/D/Stable diffusion/low Vram/LoraLowVRAMSettings.json
Traceback (most recent call last):
  File "K:\D\Kohya\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "K:\D\Kohya\kohya_ss\train_network.py", line 135, in train
    network.load_weights(args.network_weights)
  File "K:\D\Kohya\kohya_ss\networks\lora.py", line 134, in load_weights
    self.weights_sd = torch.load(file, map_location='cpu')
  File "K:\D\Kohya\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "K:\D\Kohya\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
Traceback (most recent call last):
  File "C:\Users\GIGABYTE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\GIGABYTE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "K:\D\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "K:\D\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "K:\D\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "K:\D\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['K:\\D\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--v2', '--enable_bucket', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-2-1-base', '--train_data_dir=K:/D/Kohya/KAZE STYLE LORA/image', '--resolution=512,512', '--output_dir=K:/D/Kohya/KAZE STYLE LORA/model', '--logging_dir=K:/D/Kohya/KAZE STYLE LORA/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--network_weights=K:/D/Stable diffusion/low Vram/LoraLowVRAMSettings.json', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=790', '--train_batch_size=1', '--max_train_steps=7900', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--bucket_reso_steps=64', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by Mctwost** [comment]
Did you manage to solve it? i still get text_encoder\model.safetensors not found and my 2.1 loras are not working
