### ISSUE TITLE
[question] More info about "--sample_prompts" needed

### ISSUE THREAD

**Issue by neojam** [kohya-ss/sd-scripts#256]
Hallo,

I've a question about the new "--sample_prompts" feature:

> _**--sample_prompts option: the file contains prompts (each line generates one image.)
>     The prompt is subset of gen_img_diffusers.py. The prompt options w, h, d, l, s, n are supported.**_

What are those "w, h, d, l, s, n" options and how to use them with --sample_prompts?

P.S.
Currently i just point it to a textfile containing promts and it gives me 512x512 previews during training.
--sample_prompts="D:\SDTEST\Promts.txt"
But I have no Idea how to use the "w, h, d, l, s, n" options and what those are.

**Comment by neojam** [comment]
Looks like you can add those **after** your promt inside the txt file: --w 512 --h 768 --s 35.
still need info about: d, l, n

**Comment by neojam** [comment]
Not a problem at all and thank you a lot for the clarification! :)

**Comment by DarkAlchy** [comment]
--d my seed is the only one of those flags that is not shown in the cli.  Is it ignoring it?
