### ISSUE TITLE
Config_util.py is not python 3.8/3.9 compatible

### ISSUE THREAD

**Issue by AI-Casanova** [kohya-ss/sd-scripts#259]
Google Colab will be migrating from Python 3.8 to 3.9 in the coming weeks, but from another issue here, that still will not make the newest PR compatible for a lot of people without GPUs

Is there any way you could refactor the TOML checking to make it backwards compatible for those of us stuck with Python 3.8/3.9?

**Comment by Linaqruf** [comment]
Hi, I think there is another issue after recent commit
```python
Traceback (most recent call last):
  File "train_network.py", line 21, in <module>
    import library.config_util as config_util
  File "/content/kohya-trainer/library/config_util.py", line 114, in <module>
    class ConfigSanitizer:
  File "/content/kohya-trainer/library/config_util.py", line 170, in ConfigSanitizer
    "resolution": functools.partial(__validate_and_convert_scalar_or_twodim, int),
TypeError: the first argument must be callable
```

dataset_config.toml
```toml

[general]
enable_bucket = true
cache_latents = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64
bucket_no_upscale = false
flip_aug = false

[[datasets]]
resolution = 512
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
caption_dropout_rate = 0
caption_tag_dropout_rate = 0
caption_dropout_every_n_epochs = 0

[[datasets.subsets]]
image_dir = "/content/LoRA/train_data"
class_tokens = "sks 1girl"
num_repeats = 10

[[datasets.subsets]]
is_reg = true
image_dir = "/content/LoRA/reg_data"
class_tokens = "1girl"
num_repeats = 1

```

**Comment by AI-Casanova** [comment]
Reading through https://docs.python.org/3/whatsnew/3.10.html

The only change that makes sense to me is https://peps.python.org/pep-0612/ though I need to study it more to make sure, and see if there is a path forward.

**Comment by AI-Casanova** [comment]
Oh wait
`Static methods (@staticmethod) and class methods (@classmethod) now inherit the method attributes (__module__, __name__, __qualname__, __doc__, __annotations__) and have a new __wrapped__ attribute. Moreover, static methods are now callable as regular functions. `

Is is simply the @static_method decorator causing the callable error?

**Comment by AI-Casanova** [comment]
newest error for me
`Traceback (most recent call last):
  File "train_network.py", line 642, in <module>
    train(args)
  File "train_network.py", line 65, in train
    blueprint_generator = BlueprintGenerator(ConfigSanitizer(True, True, True))
  File "/content/sd-scripts/library/config_util.py", line 193, in __init__
    self.db_subset_schema = self.__merge_dict(
  File "/content/sd-scripts/library/config_util.py", line 286, in __merge_dict
    merged |= schema
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'`

**Comment by Linaqruf** [comment]
I'm changed `= |` with `update()` that compatible with py3.8, and it works fine

```python
  def __merge_dict(*dict_list: dict) -> dict:
    merged = {}
    for schema in dict_list:
      merged.update(schema)
    return merged
```

**Comment by AI-Casanova** [comment]
Can confirm @Linaqruf 's fix, training underway on Colab!

**Comment by camenduru** [comment]
thanks @kohya-ss ❤

**Comment by camenduru** [comment]
Hi @Linaqruf 👋 Hi @AI-Casanova 👋 thanks for the issue ❤ maybe we also need this https://github.com/kohya-ss/sd-scripts/pull/261
