### ISSUE TITLE
replace_unet_cross_attn_to_memory_efficient.<locals>.forward_flash_attn() got an unexpected keyword argument 'encoder_hidden_states'

### ISSUE THREAD

**Issue by kopyl** [kohya-ss/sd-scripts#337]
I run:

```sd-scripts/gen_img_diffusers.py --ckpt=v1-5-pruned.ckpt --outdir=outputs2 --seed=1 --network_module=networks.lora --network_weights=100img_1-5.safetensors --prompt="man on the moon"```

I get this error:

```TypeError: replace_unet_cross_attn_to_memory_efficient.<locals>.forward_flash_attn() got an unexpected keyword argument 'encoder_hidden_states'```

Full code: https://pastebin.com/pxG3YSXi

How to fix it?

**Comment by kopyl** [comment]
fixed. Was missing requirements

**Comment by Yaodada12** [comment]
> fixed. Was missing requirements

I got the same problem, which package was missing？
