### ISSUE TITLE
Error during windows installation, RESOLVED

### ISSUE THREAD

**Issue by Revasekard** [kohya-ss/sd-scripts#37]
I'm going along the steps and I'm getting an error during the :
cp .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes\
![kT4fN2p 1](https://user-images.githubusercontent.com/120601546/210257894-ece67e64-9f25-440a-bea3-b865ec3bda55.png)

I'm on windows 11

**Comment by geocine** [comment]
May I see your folder structure and where you are running the script? The script needs to be run inside the repository folder where `bitsandbytes_windows` folder exist.

**Comment by Revasekard** [comment]
> May I see your folder structure and where you are running the script? The script needs to be run inside the repository folder where `bitsandbytes_windows` folder exist.
![qdg4eqM 1](https://user-images.githubusercontent.com/120601546/210296431-d70e4b72-fdcd-4e83-b8ff-3a0d188def08.png)
![dcXV55d 1](https://user-images.githubusercontent.com/120601546/210296438-3f7a22a0-a23b-4d3c-8c6f-8898c91f9351.png)

**Comment by geocine** [comment]
Okay can you execute this because last time you were not on the `sd-scripts` directory
1st Screenshot - Notice you were on `E:\` not on `E:\sd-scripts`
![image](https://user-images.githubusercontent.com/507464/210304225-d7474284-7027-438c-b4b1-9158af1dbb20.png)
2nd Screenshot - This is correct you are inside `E:\sd-scripts` because `bitsandbytes_windows` is inside `E:\sd-scripts`
![image](https://user-images.githubusercontent.com/507464/210304290-a5a461b2-c298-403e-bb9b-4d3625c19cd6.png)

When you are executing the commands you should be inside `E:\scripts`

**Comment by Revasekard** [comment]
Yeah the 1st shot was me just trying out things and seeing if there was a way to work around it. It reads like it isn't creating the proper folder destination for the files being copied to.
![FABdXPm 1](https://user-images.githubusercontent.com/120601546/210306443-4366599a-02e9-4e2c-8a9b-3f65eaf5dd7f.png)

At the end I just copied the files into the folders manually. Although I still barely know how to get this setup going or the setup not function properly.

**Comment by geocine** [comment]
If `bitsandbytes` folder is not present inside `.vent` . It might not have been installed try installing it directly.

Activate the venv first.
```sh
pip install bitsandbytes==0.35.0
```
Then try the copy commands again

**Comment by Revasekard** [comment]
Ok I think the problem is that my files are being directed to my python install instead of the sd-scripts folder?
![gnD5Jwt 1](https://user-images.githubusercontent.com/120601546/210654444-97ffc5a0-9f55-4cf5-b937-d167bba6310c.jpeg)

**Comment by Revasekard** [comment]
I think manually copying the files worked. Managed to find and run a script that ran things for abit. Things loaded up then killed my display drivers briefly nuking my browser.
![SOjF5EP 1](https://user-images.githubusercontent.com/120601546/210678610-3b237c8a-60f3-49e5-9f6b-a46aa8f92e5d.png)

**Comment by Revasekard** [comment]
So I had the wrong python version loading in despite having installed 3.10.6, and didn't know the PS/venv could have different versions.

Had to go into environment variables and made sure 3.10.6 was on top of the list for priorty
![5tRxHLL 1](https://user-images.githubusercontent.com/120601546/210684978-59f53b0e-fdd3-4906-a1a0-54b2d17185fb.png)
