### ISSUE TITLE
[BUG] Getting a bug in xformers

### ISSUE THREAD

**Issue by usamaa-saleem** [kohya-ss/sd-scripts#370]
`/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/safetensors/torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/torch/storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Disable Diffusers' xformers
Replace CrossAttention.forward to use xformers
[Dataset 0]
caching latents.
0it [00:00, ?it/s]
prepare optimizer, data loader etc.
use Lion optimizer | {}
override steps. steps for 200 epochs is / 指定エポックまでのステップ数: 146000
running training / 学習開始
  num examples / サンプル数: 15000
  num batches per epoch / 1epochのバッチ数: 730
  num epochs / epoch数: 200
  batch size per device / バッチサイズ: 1   
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 146000
steps:   0%|                                                                                                                                                      | 0/146000 [00:00<?, ?it/s]epoch 1/200

  File "/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/tools/sd-scripts/library/train_util.py", line 1790, in forward_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる
  File "/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 196, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 294, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 310, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 98, in _dispatch_fw
    return _run_priority_list(
  File "/home/ubuntu/tools/sd-scripts/.venv/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 73, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(24, 9126, 5, 64) (torch.float32)
     key         : shape=(24, 9126, 5, 64) (torch.float32)
     value       : shape=(24, 9126, 5, 64) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})`

**Comment by usamaa-saleem** [comment]
Please help with this

**Comment by kgonia** [comment]
what version of xformes you have?

**Comment by usamaa-saleem** [comment]
> 

xformers                     0.0.18

**Comment by kgonia** [comment]
and pytorch version? 
From my experience 0.18 is working with PyTorch 2.0 
for earlier versions is better to install 0.16

**Comment by usamaa-saleem** [comment]
I am using PyTorch 2.0

**Comment by potatoker** [comment]
same error here PyTorch 2.0 and xformers-0.0.19.

stable diffusion webui had the same error previously， but can be fixed by adding --xformers augment when launch to fix

**Comment by lastYoueven** [comment]
kohya-ss Disable Diffusers' xformers

**Comment by min-star** [comment]
> kohya-ss Disable Diffusers' xformers

me too
