### ISSUE TITLE
Accelerator acting like my GPU is not present?

### ISSUE THREAD

**Issue by TumnusB** [kohya-ss/sd-scripts#39]
accelerator.py not detecting my GPU

File "E:\sd-scripts\train_network.py", line 1453, in <module>
    train(args)
  File "E:\sd-scripts\train_network.py", line 1017, in train
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "E:\sd-scripts\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU

(venv) PS E:\sd-scripts> python
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec 6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
1
>>> torch.cuda.current_device()
0
>>> torch.cuda.device(0)
<torch.cuda.device object at 0x000002DA22E42F50>
>>> torch.cuda.get_device_name(0)
'NVIDIA GeForce RTX 4090'

**Comment by rsm28** [comment]
During the "accelerate config" step, on the GPU step, instead of "All", do "0" (if you have one GPU). That number is the ID of the GPU you want to use. "All" doesn't seem to work for me either.

**Comment by geocine** [comment]
`All` will no work because its case sensitive you need to type `all`

**Comment by lolxdmainkaisemaanlu** [comment]
having this same issue...

**Comment by JSarvise** [comment]
Tried to do it with 0 and still getting the same error

  File "C:\Users\friky\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\friky\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\friky\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'train_network.py', '--network_module=networks.lora', '--pretrained_model_name_or_path=C:\\stable-diffusion-webui\\models\\Stable-diffusion\\animefinal-full-pruned.ckpt', '--train_data_dir=D:\\image\\img', '--reg_data_dir=D:\\image\\reg', '--output_dir=D:\\image\\model', '--caption_extension=.txt', '--shuffle_caption', '--prior_loss_weight=1', '--resolution=512', '--enable_bucket', '--min_bucket_reso=320', '--max_bucket_reso=960', '--train_batch_size=8', '--learning_rate=0.0001', '--max_train_steps=590', '--mixed_precision=fp16', '--save_precision=fp16', '--use_8bit_adam', '--xformers', '--save_every_n_epochs=3', '--save_model_as=safetensors', '--clip_skip=2', '--seed=23', '--network_dim=128', '--max_token_length=150', '--cache_latents', '--lr_scheduler=cosine_with_restarts']' returned non-zero exit status 1.

Any idea what might be going on? Trying to train on a 1080 ti

**Comment by TumnusB** [comment]
loading text encoder: <All keys matched successfully>
Replace CrossAttention.forward to use xformers
caching latents.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:30<00:00,  2.82s/it]
import network module: networks.lora
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary E:\sd-scripts\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit Adam optimizer
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 50
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 8
  num epochs / epoch数: 7
  batch size per device / バッチサイズ: 8
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 8
  gradient ccumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 50
steps:   0%|                                                                                                                                                                                                         | 0/50 [00:00<?, ?it/s]epoch 1/7
[WinError 127] The specified procedure could not be found
WARNING:root:WARNING: [WinError 127] The specified procedure could not be found
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
[WinError 127] The specified procedure could not be found
WARNING:root:WARNING: [WinError 127] The specified procedure could not be found
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
[WinError 127] The specified procedure could not be found
WARNING:root:WARNING: [WinError 127] The specified procedure could not be found
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
[WinError 127] The specified procedure could not be found
WARNING:root:WARNING: [WinError 127] The specified procedure could not be found
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
[WinError 127] The specified procedure could not be found
WARNING:root:WARNING: [WinError 127] The specified procedure could not be found
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
[WinError 127] The specified procedure could not be found
WARNING:root:WARNING: [WinError 127] The specified procedure could not be found
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
[WinError 127] The specified procedure could not be found
WARNING:root:WARNING: [WinError 127] The specified procedure could not be found
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
[WinError 127] The specified procedure could not be found
WARNING:root:WARNING: [WinError 127] The specified procedure could not be found
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
Traceback (most recent call last):
  File "E:\sd-scripts\train_network.py", line 1453, in <module>
    train(args)
  File "E:\sd-scripts\train_network.py", line 1278, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "E:\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\sd-scripts\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "E:\sd-scripts\venv\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "E:\sd-scripts\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "E:\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\sd-scripts\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 612, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "E:\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\sd-scripts\venv\lib\site-packages\diffusers\models\attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "E:\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\sd-scripts\venv\lib\site-packages\diffusers\models\attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "E:\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\sd-scripts\train_network.py", line 877, in forward_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)        # 最適なのを選んでくれる
  File "E:\sd-scripts\venv\lib\site-packages\xformers\ops.py", line 865, in memory_efficient_attention
    return op.apply(query, key, value, attn_bias, p).reshape(output_shape)
  File "E:\sd-scripts\venv\lib\site-packages\xformers\ops.py", line 319, in forward
    out, lse = cls.FORWARD_OPERATOR(
  File "E:\sd-scripts\venv\lib\site-packages\xformers\ops.py", line 46, in no_such_operator
    raise RuntimeError(
RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?
steps:   0%|                                                                                                                                                                                                         | 0/50 [01:25<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\person\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\person\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "E:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "E:\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--network_module=networks.lora', '--pretrained_model_name_or_path=E:\\stable-diffusion-webui\\models\\Stable-diffusion\\animefull-final-pruned.ckpt', '--train_data_dir=C:\\Users\\person\\Pictures\\\\IMG', '--reg_data_dir=C:\\Users\\person\\Pictures\\imgset\\Reg_Imgs', '--output_dir=C:\\Users\\person\\Pictures\\imgset\\Output', '--caption_extension=.txt', '--prior_loss_weight=1', '--resolution=512', '--enable_bucket', '--min_bucket_reso=320', '--max_bucket_reso=960', '--train_batch_size=8', '--learning_rate=0.0001', '--max_train_steps=50', '--mixed_precision=fp16', '--save_precision=fp16', '--use_8bit_adam', '--xformers', '--save_every_n_epochs=99999', '--save_model_as=safetensors', '--clip_skip=2', '--seed=23', '--network_dim=128', '--max_token_length=150', '--cache_latents', '--lr_scheduler=cosine_with_restarts']' returned non-zero exit status 1.

So now theres a issue with xformers

**Comment by TumnusB** [comment]
i updated it to cu117 so moving back to cu116 and updasting the cudnn dlls fixed all my issues.

**Comment by kopyl** [comment]
@TumnusB how to update the cudnn dlls ?

**Comment by geocine** [comment]
> @TumnusB how to update the cudnn dlls . 

1. Download  your desired cudnn version https://developer.nvidia.com/rdp/cudnn-archive . I use 11.8 as that is what my GPU supports
 - (11.8) https://developer.nvidia.com/compute/cudnn/secure/8.6.0/local_installers/11.8/cudnn-windows-x86_64-8.6.0.163_cuda11-archive.zip
3. Extract and copy the files inside bin to .\venv\Lib\site-packages\torch\lib, paste and replace.

**Comment by kopyl** [comment]
Guys, i found a temp solution: https://github.com/kohya-ss/sd-scripts/issues/362
