### ISSUE TITLE
xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by DarkAlchy** [kohya-ss/sd-scripts#40]
Following the install instruction then copied and pasted the line for xformers and BOOM, YET that is the one Automatic1111 is using.

**Comment by geocine** [comment]
Is your python version 3.10?

**Comment by DarkAlchy** [comment]
yes

**Comment by Revasekard** [comment]
Try, python --version 
In the powershell then again in the venv. 

If it doesn't read 3.10 you gotta go into environment variables and shift 3.10 to the top of the PATH list. Or just uninstall all python versions and install 3.10.

**Comment by DarkAlchy** [comment]
![image](https://user-images.githubusercontent.com/10561690/210929660-2c39348f-da0d-4d58-ac51-515ef2ba6738.png)
I am in you venv YET it is saying your stuff is too old.
![image](https://user-images.githubusercontent.com/10561690/210929803-b6a40508-59b8-4d03-a668-8ad0a9202963.png)

**Comment by DarkAlchy** [comment]
What do you think I said that I did above?  Seriously?

I give up on this but thanks anyway.
