### ISSUE TITLE
feature request: support for controlnet train

### ISSUE THREAD

**Issue by sdbds** [kohya-ss/sd-scripts#456]
see here↓
https://github.com/huggingface/diffusers/tree/main/examples/controlnet

**Comment by Isotr0py** [comment]
Good idea. But `train_controlnet.py` require the latest diffusers (maybe `diffusers>=0.14.0` can also work) to use `ControlNetModel` and `StableDiffusionControlNetPipeline`.
Anyway, I just updated diffusers to 0.16.0, tested it on `train_db.py` and get these:
```
Traceback (most recent call last):
  File "/root/content/sd-scripts/train_db.py", line 467, in <module>
Traceback (most recent call last):
  File "/root/content/sd-scripts/train_db.py", line 467, in <module>
    train(args)
  File "/root/content/sd-scripts/train_db.py", line 113, in train
    train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers)
  File "/root/content/sd-scripts/library/train_util.py", line 1771, in replace_unet_modules
    train(args)
  File "/root/content/sd-scripts/train_db.py", line 113, in train
    train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers)
  File "/root/content/sd-scripts/library/train_util.py", line 1771, in replace_unet_modules
    replace_unet_cross_attn_to_xformers()
  File "/root/content/sd-scripts/library/train_util.py", line 1854, in replace_unet_cross_attn_to_xformers
    diffusers.models.attention.CrossAttention.forward = forward_xformers
AttributeError: module 'diffusers.models.attention' has no attribute 'CrossAttention'
    replace_unet_cross_attn_to_xformers()
  File "/root/content/sd-scripts/library/train_util.py", line 1854, in replace_unet_cross_attn_to_xformers
    diffusers.models.attention.CrossAttention.forward = forward_xformers
AttributeError: module 'diffusers.models.attention' has no attribute 'CrossAttention'
```
So, I think we can update the scripts to support new version diffusers and accelerate (#311) first.

**Comment by Isotr0py** [comment]
Oh, I found it. It's much simpler than diffusers' implementation!

**Comment by alelordelo** [comment]
@sdbds @Isotr0py @kohya-ss @lansing @rockerBOO,

did you guys see this?
https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md

Does kohya support ControlNET training now?

**Comment by sdbds** [comment]
> @sdbds @Isotr0py @kohya-ss @lansing @rockerBOO,
> 
> did you guys see this? https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md
> 
> Does kohya support ControlNET training now?

Yes, now we can train controlnet-lllite for SDXL, kohya will make a SD15 version for it.

**Comment by sdbds** [comment]
> @sdbds , where is the ControlNET SDXL trainner? Is there a Google Colab for it?

i dont know if kohya_ss add it, but i can use this repo to train now

**Comment by alelordelo** [comment]
> > @sdbds , where is the ControlNET SDXL trainner? Is there a Google Colab for it?
> 
> i dont know if kohya_ss add it, but i can use this repo to train now

do you mind sharing a link to the script? is it stable?

**Comment by sdbds** [comment]
> > > @sdbds , where is the ControlNET SDXL trainner? Is there a Google Colab for it?
> > 
> > 
> > i dont know if kohya_ss add it, but i can use this repo to train now
> 
> do you mind sharing a link to the script? is it stable?

https://civitai.com/models/118694
