### ISSUE TITLE
I can't start training

### ISSUE THREAD

**Issue by ppkppk8520** [kohya-ss/sd-scripts#46]
Traceback (most recent call last):
  File "G:\kohya\sd-scripts\train_db.py", line 1229, in <module>
    train(args)
  File "G:\kohya\sd-scripts\train_db.py", line 1043, in train
    encoder_hidden_states = text_encoder.text_model.final_layer_norm(encoder_hidden_states)
  File "G:\kohya\sd-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\kohya\sd-scripts\venv\lib\site-packages\torch\nn\modules\normalization.py", line 189, in forward
    return F.layer_norm(
  File "G:\kohya\sd-scripts\venv\lib\site-packages\torch\nn\functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Float but found Half
steps:   0%|                                                                                  | 0/3000 [00:34<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\username\miniconda3\envs\kohya\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\miniconda3\envs\kohya\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\kohya\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "G:\kohya\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "G:\kohya\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "G:\kohya\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['G:\\kohya\\sd-scripts\\venv\\Scripts\\python.exe', 'train_db.py', '--pretrained_model_name_or_path=G:\\stable-diffusion-webui\\models\\Stable-diffusion\\Anything-V3.0-pruned.ckpt', '--train_data_dir=G:\\kohya\\dataset\\train', '--output_dir=G:\\kohya\\results', '--prior_loss_weight=1.0', '--resolution=512', '--train_batch_size=1', '--learning_rate=1e-6', '--max_train_steps=3000', '--use_8bit_adam', '--xformers', '--mixed_precision=fp16', '--cache_latents', '--caption_extention=.txt', '--clip_skip=2', '--full_fp16', '--gradient_checkpointing']' returned non-zero exit status 1.

i'm using windows10 and 3080 10gb.
may using conda cause this problem?

thanks in advance.

**Comment by ppkppk8520** [comment]
thanks!

**Comment by 5nail000** [comment]
Hi! I have such issue, but at train_textual_inversion.py

```
python /workspace/kohya-trainer/train_textual_inversion.py \
  --dataset_config="/workspace/train/configs/ti_dataset_config.toml" \
  --train_data_dir="/workspace/train/inputs/" \
  --resolution=512 \
  --train_batch_size=1 \
  --dataset_repeats=10 \
  --keep_tokens=0 \
  --max_train_epochs=3 \
  --output_dir="/workspace/train/outputs/" \
  --output_name="timodel" \
  --save_precision="fp16" \
  --learning_rate=1e-6 \
  --init_word="*" \
  --token_string="loromodeltoken" \
  --num_vectors_per_token=1 \
  --mixed_precision="fp16" \
  --prior_loss_weight=1.0 \
  --use_object_template \
  --use_8bit_adam \
  --cache_latents \
  --gradient_checkpointing \
  --pretrained_model_name_or_path="/workspace/pretrained_model/Deliberate_v2.safetensors"
 ```

dataset.toml:
```
[general]
enable_bucket = true
shuffle_caption = true
caption_extension = 'none'
keep_tokens = 0
bucket_reso_steps = 64
bucket_no_upscale = false

[[datasets]]
resolution = 512
min_bucket_reso = 128
max_bucket_reso = 1024
batch_size = 1

  [[datasets.subsets]]
  image_dir = "/workspace/train/inputs"
  class_tokens = "timodel"
  num_repeats = 10

  [[datasets.subsets]]
  is_reg = false
  image_dir = "/workspace/train/reg_images"
  class_tokens = "person"
  num_repeats = 0
```

**RuntimeError: expected scalar type Float but found Half
steps:   0%|**

**Comment by 5nail000** [comment]
Hi! I have such issue, but at train_textual_inversion.py

```
python /workspace/kohya-trainer/train_textual_inversion.py \
  --dataset_config="/workspace/train/configs/ti_dataset_config.toml" \
  --train_data_dir="/workspace/train/inputs/" \
  --resolution=512 \
  --train_batch_size=1 \
  --dataset_repeats=10 \
  --keep_tokens=0 \
  --max_train_epochs=3 \
  --output_dir="/workspace/train/outputs/" \
  --output_name="timodel" \
  --save_precision="fp16" \
  --learning_rate=1e-6 \
  --init_word="*" \
  --token_string="loromodeltoken" \
  --num_vectors_per_token=1 \
  --mixed_precision="fp16" \
  --prior_loss_weight=1.0 \
  --use_object_template \
  --use_8bit_adam \
  --cache_latents \
  --gradient_checkpointing \
  --pretrained_model_name_or_path="/workspace/pretrained_model/Deliberate_v2.safetensors"
```

**dataset.toml:**
```
[general]
enable_bucket = true
shuffle_caption = true
caption_extension = 'none'
keep_tokens = 0
bucket_reso_steps = 64
bucket_no_upscale = false

[[datasets]]
resolution = 512
min_bucket_reso = 128
max_bucket_reso = 1024
batch_size = 1

  [[datasets.subsets]]
  image_dir = "/workspace/train/inputs"
  class_tokens = "timodel"
  num_repeats = 10

  [[datasets.subsets]]
  is_reg = false
  image_dir = "/workspace/train/reg_images"
  class_tokens = "person"
  num_repeats = 0
```

**RuntimeError: expected scalar type Float but found Half
steps: 0%|**

**Comment by 5nail000** [comment]
> The full_fp16 option seems to cause a problem. I reproduce the issue with clip_skip=2. Without clip_skip, it works.
> 
> I will fix with this issue with the refactoring task. Please wait a moment.


**Hi! I have such issue, but at train_textual_inversion.py**
```
python /workspace/kohya-trainer/train_textual_inversion.py \
  --dataset_config="/workspace/train/configs/ti_dataset_config.toml" \
  --train_data_dir="/workspace/train/inputs/" \
  --resolution=512 \
  --train_batch_size=1 \
  --dataset_repeats=10 \
  --keep_tokens=0 \
  --max_train_epochs=3 \
  --output_dir="/workspace/train/outputs/" \
  --output_name="timodel" \
  --save_precision="fp16" \
  --learning_rate=1e-6 \
  --init_word="*" \
  --token_string="loromodeltoken" \
  --num_vectors_per_token=1 \
  --mixed_precision="fp16" \
  --prior_loss_weight=1.0 \
  --use_object_template \
  --use_8bit_adam \
  --cache_latents \
  --gradient_checkpointing \
  --pretrained_model_name_or_path="/workspace/pretrained_model/Deliberate_v2.safetensors"
```

**dataset.toml:**
```
[general]
enable_bucket = true
shuffle_caption = true
caption_extension = 'none'
keep_tokens = 0
bucket_reso_steps = 64
bucket_no_upscale = false

[[datasets]]
resolution = 512
min_bucket_reso = 128
max_bucket_reso = 1024
batch_size = 1

  [[datasets.subsets]]
  image_dir = "/workspace/train/inputs"
  class_tokens = "timodel"
  num_repeats = 10

  [[datasets.subsets]]
  is_reg = false
  image_dir = "/workspace/train/reg_images"
  class_tokens = "person"
  num_repeats = 0
```

**RuntimeError: expected scalar type Float but found Half
steps: 0%|**
