### ISSUE TITLE
Question about block weight

### ISSUE THREAD

**Issue by zyd232** [kohya-ss/sd-scripts#470]
### Discussed in https://github.com/kohya-ss/sd-scripts/discussions/469

<div type='discussions-op-text'>

<sup>Originally posted by **zyd232** May  1, 2023</sup>
There are 17 blocks in a LoRA:
<html>
<body>

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BASE | IN01 | IN02 | IN04 | IN05 | IN07 | IN08 | MID | OUT03 | OUT04 | OUT05 | OUT06 | OUT07 | OUT08 | OUT09 | OUT10 | OUT11

</body>
</html>

But, there are 25 blocks to fill in the trainning scripts. And I found the following words in kohya's updates:
`No LoRA corresponds to the first block, but 25 blocks are specified for compatibility with 'LoRA block weight' etc. `

Someone please tell me the correspondence between the 17 blocks in LoRA and the 25 blocks in the training parameters.

</div>

**Comment by WSH032** [comment]
**You can get it here [hako-mikan/sd-webui-lora-block-weight](https://github.com/hako-mikan/sd-webui-lora-block-weight)**

- For lora:

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BASE | IN01 | IN02 | IN04 | IN05 | IN07 | IN08 | MID | OUT03 | OUT04 | OUT05 | OUT06 | OUT07 | OUT08 | OUT09 | OUT10 | OUT11

- For LyCORIS, etc.

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BASE | IN00 | IN01 | IN02 | IN03 | IN04 | IN05 | IN06 | IN07 | IN08 | IN09 | IN10 | IN11 | MID | OUT00 | OUT01 | OUT02 | OUT03 | OUT04 | OUT05 | OUT06 | OUT07 | OUT08 | OUT09 | OUT10 | OUT11

- In kohya-sd-scripts, there is no BASE

**Comment by zyd232** [comment]
> **You can get it here [hako-mikan/sd-webui-lora-block-weight](https://github.com/hako-mikan/sd-webui-lora-block-weight)**
> 
> * For lora:
> 
> 1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17
> BASE	IN01	IN02	IN04	IN05	IN07	IN08	MID	OUT03	OUT04	OUT05	OUT06	OUT07	OUT08	OUT09	OUT10	OUT11
> * For LyCORIS, etc.
> 
> 1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25	26
> BASE	IN00	IN01	IN02	IN03	IN04	IN05	IN06	IN07	IN08	IN09	IN10	IN11	MID	OUT00	OUT01	OUT02	OUT03	OUT04	OUT05	OUT06	OUT07	OUT08	OUT09	OUT10	OUT11
> * In kohya-sd-scripts, there is no BASE

So, if there are 25 blocks, the 25 blocks for LoRA should be like the following:

<html>
<body>


1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
**N/A** | IN01 | IN02 | **N/A** | IN04 | IN05 | **N/A** | IN07 | IN08 | **N/A** | **N/A** | **N/A** | MID | **N/A** | **N/A** | **N/A** | OUT03 | OUT04 | OUT05 | OUT06 | OUT07 | OUT08 | OUT09 | OUT10 | OUT11


</body>
</html>
When I set the training parameters for block weight, the parameters for IN00, IN03, IN06, IN09, IN10, IN11, OUT00, OUT01 and OUT02 should be 0 as default. Am I correct?

**Comment by WSH032** [comment]
> > **You can get it here [hako-mikan/sd-webui-lora-block-weight](https://github.com/hako-mikan/sd-webui-lora-block-weight)**
> > 
> > * For lora:
> > 
> > 1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17
> > BASE	IN01	IN02	IN04	IN05	IN07	IN08	MID	OUT03	OUT04	OUT05	OUT06	OUT07	OUT08	OUT09	OUT10	OUT11
> > 
> > * For LyCORIS, etc.
> > 
> > 1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25	26
> > BASE	IN00	IN01	IN02	IN03	IN04	IN05	IN06	IN07	IN08	IN09	IN10	IN11	MID	OUT00	OUT01	OUT02	OUT03	OUT04	OUT05	OUT06	OUT07	OUT08	OUT09	OUT10	OUT11
> > 
> > * In kohya-sd-scripts, there is no BASE
> 
> So, if there are 25 blocks, the 25 blocks for LoRA should be like the following:
> 
> 1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25
> **N/A**	IN01	IN02	**N/A**	IN04	IN05	**N/A**	IN07	IN08	**N/A**	**N/A**	**N/A**	MID	**N/A**	**N/A**	**N/A**	OUT03	OUT04	OUT05	OUT06	OUT07	OUT08	OUT09	OUT10	OUT11When I set the training parameters for block weight, the parameters for IN00, IN03, IN06, IN09, IN10, IN11, OUT00, OUT01 and OUT02 should be 0 as default. Am I correct?

---

Probably？

I don't exactly know how `kohya-ss` works. Sorry for that. 

But, i usually set 1 for them, because  [hako-mikan/sd-webui-lora-block-weight](https://github.com/hako-mikan/sd-webui-lora-block-weight) does the same thing.
