### ISSUE TITLE
how to train with captions and regularization images?

### ISSUE THREAD

**Issue by felixsanz** [kohya-ss/sd-scripts#524]
Hi!

If i want to use captions... does it affect the instance prompt and the class prompt? or it's still "asd" and "person" ?

And for example, how a caption should look like?

A) "photo of asd wearing a yellow shirt"
B) "photo of asd person wearing a yellow shirt"
C) other?

And how i do generate the regularization images?  "photo of person wearing a yellow shirt" ?? how many is ok?

Thanks in advance

**Comment by svupper** [comment]
Hello,
I was asking myself the same question, I ended up generating reg images using the same caption generated by the tagger( without the instance prompt) for each image of my training dataset. I then add the instance prompt to the captions using: sed -i 's/{INSTANCE_CLASS}/{INSTANCE_PROMPT} {INSTANCE_CLASS}/g' *.txt 
But I don't know if the regularization images need a caption file .txt and if we need to keep the same ratio as the training images :/

**Comment by push2t** [comment]
regularisation files do try to read a caption file, but they do not 'need' one, in that training will still proceed without a caption, i believe just with undefined and probably bad results. infact all training in kohya can happen without a caption, it just doesnt do anything very useful.

i am also unsure about the ratio question, as my observation is that once your reg images are added, they are iterated through with your training images in the same frequency, its training images + reg images until you run out of steps, so the amount of reg images seems to be important.

**Comment by svupper** [comment]
@push2t I mean the size dimensions of the regularization images. Should we use regularization images with the same size as our training bucket ? and making sure the captions match the ones used for generating the reg images? for exemple:

Training set:
768,512 : 2 (caption: a man in suit)
512,512: 1 (caption: a man sitting)

Reg images:
768,512: 80 (2 x 40, if 40 repetitions) (generated with this caption: a man in suit)
512,512: 40 (1 x 40, if 40 repetitions) (generated with this caption: a man sitting)
