### ISSUE TITLE
[bug] Bucketing algorithm is incorrect in marginal cases

### ISSUE THREAD

**Issue by ash0080** [kohya-ss/sd-scripts#543]
I have four different resolutions,  512x512, 512x768, 512x640, 768x512, all images
but the script is giving me the same lower resolution for all of them except for 1:1. 
This doesn't seem reasonable.

<img width="356" alt="2023-05-27 200024" src="https://github.com/kohya-ss/sd-scripts/assets/2803210/09c20c01-adb7-47af-a8c8-a0542066b380">

**Comment by ash0080** [comment]
> The resolution parameter sets the max pixels that the image can have if the image size is higher it scales it down to the nearest multiple of 64 if you want to have 512x768 bucket sizes you need resolution to be at least 640 not 512 which is what it seems to be

I don't understand. My image sizes have all been pre-processed and are already in the correct size, just waiting to be bucketed. Are you saying that even though my images are already 512 in size, I need to set them to 640 or else it will scale them down to 384? Is that reasonable?

**Comment by ash0080** [comment]
> The total image pixels sets the max amount of pixels the images can have at 512*512 it's around 245'000 pixels 512x768 is more than that so it's gets scaled down

So I think the situation you described is somewhat different from what I faced.

min bucket res 512
max bucket res 1024

**Comment by ash0080** [comment]
> You need to change the resolution setting

I think I understand now. Are you saying that all the buckets must fall within a range of resolution^2?

**Comment by ash0080** [comment]
> Around there yes but the buckets use 64 pixel increments so it won't be exact

I understand now, thank you for the explanation.

**Comment by ywdong** [comment]
> 

I also met the same problem. Can u tell me how u set your setting or change your pic resolution?
