### ISSUE TITLE
Any updates on getting Cosine with annealing?

### ISSUE THREAD

**Issue by DarkAlchy** [kohya-ss/sd-scripts#601]
I asked for this from Kohya a while back, and it is not cosine with restart, only now the new Prodigy wants that to be at its best (per the dev on the github site).

Any chance?

https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.CosineAnnealingLR.html

**Comment by Isotr0py** [comment]
You can use `--lr_scheduler_type` and `--lr_scheduler_args` to set custom scheduler.
- More details in #271

**Comment by DarkAlchy** [comment]
> You can use `--lr_scheduler_type` and `--lr_scheduler_args` to set custom scheduler.
> 
> * More details in [Add '--lr_scheduler_type' and '--lr_scheduler_args' argument #271](https://github.com/kohya-ss/sd-scripts/pull/271)

WOW, that rocks if it is really that easy.

Thank you.

**Comment by DarkAlchy** [comment]
That isn't in sd-scripts though, or if it is I didn't find it, BUT is in Kohya_ss.  I need it in sd-scripts.

**Comment by dill-shower** [comment]
+1

**Comment by Isotr0py** [comment]
@DarkAlchy Just pass `--lr_scheduler_type` and `--lr_scheduler_args` to command line.
For example:
```
accelerate launch "train_network.py" ... --lr_scheduler_type "CosineAnnealingLR" --lr_scheduler_args "T_max=100"
```

**Comment by DarkAlchy** [comment]
Well, I use .toml and I wonder how sd-scripts wants those in toml format?

**Comment by Isotr0py** [comment]
It seems that `.toml` works similarly with command line args:
```
[general]
lr_scheduler_type = "CosineAnnealingLR"
lr_scheduler_args = "T_max=100"
```

I don't know how Kohya_ss gui implemented this scheduler since I seldom used it.

**Comment by DarkAlchy** [comment]
I do not know myself but I can tell you a friend worked with this over 8h with me on his 3090 and on 2.1 we nailed down some good settings that floored us.  One thing I will say is that people need to look at the specs for annealing because T_max at 100 is flat out wrong AND don't use any defaults.  We tried 100, and the defaults and after many hours of log tracing, and testing we came to this conclusion.  If anyone is training on 2.1 go to Pytorch.org and read up on the ALL the settings and you will see.

For me this sucks in one department and that is at 15GB on Colab I am forced to turn on checkpointing (else I can't even get BS1) to use what Annealing works fantastic with called Prodigy.  For Adam anything is flat out sucked.  I know why but only so many hours in a day.  Btw, with Prodigy BS1 and checkpointing it takes 13.7-13.8GB of vram.

Thank you for all this help, but I must admit I found it odd that doing a scan all files I found nothing in sd-scripts and a few hits with Kohya_ss.

**Comment by DarkAlchy** [comment]
> It seems that `.toml` works similarly with command line args:
> 
> ```
> [general]
> lr_scheduler_type = "CosineAnnealingLR"
> lr_scheduler_args = "T_max=100"
> ```
> 
> I don't know how Kohya_ss gui implemented this scheduler since I seldom used it.

I never did manage to get this to work as it says
![image](https://github.com/kohya-ss/sd-scripts/assets/10561690/04bf635d-66ab-45a6-9a94-09c88f1de561)

I inserted a print for that ars.blahblah and it showed T_max=100, or other things I tried too yet they always result in that error.  Are sure sd-scripts really does work with these?

**Comment by Isotr0py** [comment]
@DarkAlchy Oh, my fault.

It seems that `args.blahblah` just passed str instead of a list through `.toml`.

We should pass a list through `.toml`:
```
lr_scheduler_args = ['T_max=100', ...]
```

**Comment by DarkAlchy** [comment]
@Isotr0py That was the first way that I tried and it had the same issue.  I tried it as that is how we pass the other args (such as weight etc...).  Some reason it didn't grab it.

**Comment by Isotr0py** [comment]
I tested the below config on Colab and it worked normally:
```toml
[model_arguments]
v2 = false
v_parameterization = false
pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5"

[additional_network_arguments]
no_metadata = false
unet_lr = 0.0001
text_encoder_lr = 5e-5
network_module = "networks.lora"
network_dim = 64
network_alpha = 32
network_train_unet_only = false
network_train_text_encoder_only = false

[network_arguments]
network_args = [ "conv_dim=128", "conv_alpha=128", "algo=lora",]
network_train_unet_only = false
network_train_text_encoder_only = false

[optimizer_arguments]
optimizer_type = "AdamW8bit"
learning_rate = 0.0001
max_grad_norm = 1.0
optimizer_args = [ "weight_decay=0.6",]
lr_scheduler_type = "CosineAnnealingLR"
lr_scheduler_args = [ "T_max=66",]
lr_warmup_steps = 0

[dataset_arguments]
cache_latents = true
debug_dataset = false
enable_bucket = true
train_data_dir="/content/gdrive/MyDrive/Lora-train"

[training_arguments]
resolution = 512
output_dir = "/content/"
output_name = "test"
save_precision = "fp16"
save_every_n_epochs = 1
train_batch_size = 6
max_token_length = 225
mem_eff_attn = false
xformers = true
max_train_epochs = 20
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
gradient_checkpointing = false
gradient_accumulation_steps = 1
mixed_precision = "fp16"
clip_skip = 2
logging_dir = "/content/LoRA/logs"
log_prefix = "test"
noise_offset = 0.1
lowram = true
```

![QQ截图20230624194141](https://github.com/kohya-ss/sd-scripts/assets/41363108/186cf693-3929-405d-b738-3d23d52f6033)

It's strange that the value error was raised...

**Comment by DarkAlchy** [comment]
Why is my lr_scheduler_args = [ "T_max=66",] different from yours since yours worked and mine says that error of mine?

**Comment by DarkAlchy** [comment]
[model_arguments]
v2 = true
v_parameterization = true
scale_v_pred_loss_like_noise_pred = true
pretrained_model_name_or_path = "/content/drive/MyDrive/pretrained_model/V2.1/stable-diffusion-2-1-768-ema.safetensors"

[additional_network_arguments]
no_metadata = false
unet_lr = 1.0
text_encoder_lr = 1.0
network_module = "lycoris.kohya"
network_dim = 128
network_alpha = 128
network_args = [ "conv_dim=128", "conv_alpha=128", "algo=lora",]
network_train_unet_only = false
network_train_text_encoder_only = false

[optimizer_arguments]
min_snr_gamma = 1
optimizer_type = "AdamW8bit"
learning_rate = 1
max_grad_norm = 1.0
optimizer_args = [ "eps=1e-6",]
lr_scheduler = "CosineAnnealingLR"
lr_scheduler_args = "[\"T_max=66\"]"
lr_warmup_steps = 0

[dataset_arguments]
cache_latents = true
debug_dataset = false
vae_batch_size = 1

[training_arguments]
output_dir = "/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/model"
output_name = "last"
save_precision = "fp16"
save_every_n_epochs = 20
train_batch_size = 1
max_token_length = 150
mem_eff_attn = false
xformers = true
max_train_epochs = 66
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
seed = 13336
gradient_checkpointing = true
gradient_accumulation_steps = 1
mixed_precision = "fp16"
logging_dir = "/content/LoRA/logs"
log_prefix = "last"
noise_offset = 0.05
lowram = true

[sample_prompt_arguments]
sample_every_n_epochs = 20
sample_sampler = "ddim"

[dreambooth_arguments]
prior_loss_weight = 1.0

[saving_arguments]
save_model_as = "safetensors"

[[datasets]]
resolution = 768
min_bucket_reso = 320
max_bucket_reso = 1280
caption_dropout_rate = 0.75
caption_tag_dropout_rate = 0
caption_dropout_every_n_epochs = 0
flip_aug = true
color_aug = false
[[datasets.subsets]]
image_dir = "/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/img/1_mirmaask style"
class_tokens = "mirmaask style"
num_repeats = 1

[[datasets.subsets]]
image_dir = "/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/reg/1_style"
class_tokens = "style"
num_repeats = 1
is_reg = true


[general]
enable_bucket = true
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
bucket_reso_steps = 64
bucket_no_upscale = false


Loading settings from /content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/config/config_file.toml...
/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/config/config_file
prepare tokenizer
update token length: 150
Loading dataset config from /content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/config/dataset_config.toml
prepare images.
found directory /content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/img/1_mirmaask style contains 10 image files
found directory /content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/reg/1_style contains 100 image files
No caption file found for 100 images. Training will continue without captions for these images. If class token exists, it will be used. / 100枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/reg/1_style/02214-1838393807-1girl, 1boy, short hair, knife, black hair, blurry, glasses, holding, labcoat, building, profile, book, from side, city, blurry.png
/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/reg/1_style/02215-1838393808-1girl, 1boy, short hair, knife, black hair, blurry, glasses, holding, labcoat, building, profile, book, from side, city, blurry.png
/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/reg/1_style/02216-1838393809-1girl, 1boy, short hair, knife, black hair, blurry, glasses, holding, labcoat, building, profile, book, from side, city, blurry.png
/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/reg/1_style/02217-1838393810-1girl, 1boy, short hair, knife, black hair, blurry, glasses, holding, labcoat, building, profile, book, from side, city, blurry.png
/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/reg/1_style/02218-1838393811-1girl, 1boy, short hair, knife, black hair, blurry, glasses, holding, labcoat, building, profile, book, from side, city, blurry.png
/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/reg/1_style/02219-1838393812-1girl, 1boy, short hair, knife, black hair, blurry, glasses, holding, labcoat, building, profile, book, from side, city, blurry.png... and 95 more
10 train images with repeating.
100 reg images.
some of reg images are not used / 正則化画像の数が多いので、一部使用されない正則化画像があります
[Dataset 0]
  batch_size: 1
  resolution: (768, 768)
  enable_bucket: True
  min_bucket_reso: 320
  max_bucket_reso: 1280
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/img/1_mirmaask style"
    image_count: 10
    num_repeats: 1
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.75
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0
    color_aug: False
    flip_aug: True
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: mirmaask style
    caption_extension: .txt

  [Subset 1 of Dataset 0]
    image_dir: "/content/drive/MyDrive/SAMPLE_IMAGES_TRAIN/reg/1_style"
    image_count: 100
    num_repeats: 1
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.75
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0
    color_aug: False
    flip_aug: True
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: style
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100% 20/20 [00:00<00:00, 433.33it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (768, 768), count: 20
mean ar error (without repeats): 0.0
preparing accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: /content/drive/MyDrive/pretrained_model/V2.1/stable-diffusion-2-1-768-ema.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
CrossAttention.forward has been replaced to enable xformers.
import network module: lycoris.kohya
[Dataset 0]
caching latents.
100% 20/20 [00:16<00:00,  1.25it/s]
Using rank adaptation algo: lora
Use Dropout value: 0.0
Create LyCORIS Module
create LyCORIS for Text Encoder: 138 modules.
Create LyCORIS Module
create LyCORIS for U-Net: 278 modules.
enable LyCORIS for text encoder
enable LyCORIS for U-Net
preparing optimizer, data loader etc.
Deprecated: use prepare_optimizer_params(text_encoder_lr, unet_lr, learning_rate) instead of prepare_optimizer_params(text_encoder_lr, unet_lr)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
use 8-bit AdamW optimizer | {'eps': 1e-06}
override steps. steps for 66 epochs is / 指定エポックまでのステップ数: 1320
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/drive/MyDrive/kohya/train_network.py:873 in <module>                │
│                                                                              │
│   870 │   args = parser.parse_args()                                         │
│   871 │   args = train_util.read_config_from_file(args, parser)              │
│   872 │                                                                      │
│ ❱ 873 │   train(args)                                                        │
│   874                                                                        │
│                                                                              │
│ /content/drive/MyDrive/kohya/train_network.py:289 in train                   │
│                                                                              │
│   286 │   train_dataset_group.set_max_train_steps(args.max_train_steps)      │
│   287 │                                                                      │
│   288 │   # lr schedulerを用意する                                           │
│ ❱ 289 │   lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accel │
│   290 │                                                                      │
│   291 │   # 実験的機能：勾配も含めたfp16学習を行う　モデル全体をfp16にする   │
│   292 │   if args.full_fp16:                                                 │
│                                                                              │
│ /content/drive/MyDrive/kohya/library/train_util.py:2913 in get_scheduler_fix │
│                                                                              │
│   2910 │   lr_scheduler_kwargs = {}  # get custom lr_scheduler kwargs        │
│   2911 │   if args.lr_scheduler_args is not None and len(args.lr_scheduler_a │
│   2912 │   │   for arg in args.lr_scheduler_args:                            │
│ ❱ 2913 │   │   │   key, value = arg.split("=")                               │
│   2914 │   │   │                                                             │
│   2915 │   │   │   value = ast.literal_eval(value)                           │
│   2916 │   │   │   # value = value.split(",")                                │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by DarkAlchy** [comment]
I am just not getting this to work so something you have I do not have.

ValueError: 'CosineAnnealingLR' is not a valid SchedulerType

**Comment by Isotr0py** [comment]
Custom scheduler use `lr_scheduler_type` instead of `lr_scheduler` (maybe we can move this to `lr_scheduler` in future)

And it seems that `lr_scheduler_args = "["T_max=66"]"` is a wrong syntax. This will pass a str instead of a list. The right one should be `lr_scheduler_args = ["T_max=66"]` to pass a list.

So the right scheduler config is shown below:
```toml
lr_scheduler = "CosineAnnealingLR"
lr_scheduler_args = ["T_max=66"]
```

**Comment by DarkAlchy** [comment]
You contradicted yourself there.

Custom scheduler use lr_scheduler_type instead of lr_scheduler, but you are still using the same syntax as you previously did.  Not sure what yours has that downloading from the github doesn't.

**Comment by DarkAlchy** [comment]
@Isotr0py 
![image](https://github.com/kohya-ss/sd-scripts/assets/10561690/cbd50fe4-3b95-4fb1-be52-3f5fa37b03ef)

**Comment by DarkAlchy** [comment]
@Isotr0py Thank you for all of your help as I had to just change that from lr_scheduler to lr_scheduler_type.

**Comment by DarkAlchy** [comment]
How do I get this to work?

--lr_scheduler_type "CosineAnnealingLR" --lr_scheduler_args "T_max=1"  --lr_scheduler_args "eta_min=1e-4"  --lr_scheduler_args "verbose=true"

I tried "T_max=1, blah blah" I tried with a space instead and it will finally pass kohya but right before it begins the script bitch and error out.

![image](https://github.com/kohya-ss/sd-scripts/assets/10561690/4bf3e1f7-0b79-436e-add9-cc0ed5d40911)

We need all of those to be fully implemented.

**Comment by Isotr0py** [comment]
Can't reproduce the error:
```
use CosineAnnealingLR | {'T_max': 1, 'eta_min': 0.0001, 'verbose': True} as lr_scheduler
Adjusting learning rate of group 0 to 1.0000e-05.
Adjusting learning rate of group 1 to 1.0000e-04.
```

You can pass multiple args directly:
```
--lr_scheduler_type "CosineAnnealingLR" --lr_scheduler_args "T_max=1" "eta_min=1e-4" "verbose=True"
```

**Comment by DarkAlchy** [comment]
Dang, just would not work for me like that so I must have done something wrong because I copied, and pasted yours in to have it work just fine. :)

Thank you so much, again.

**Comment by DarkAlchy** [comment]
I do not use toml as I have no way to write one in the gui.  If you read the documentation Tmax is not what others think to put there (because they are flat out wrong) it is 1 for every time the scheduler.step() is called NOT the number of epochs.  When you see Tmax = 30 run.  I found it really is how the original dev wrote in their papers so uses steps.  For me I will do 200 steps and BS 12 with Tmax=200.  TBH you can put whatever you wish (good and bad) and go look at it in tensorboard to see the cosine waves.  if you make Tmax = number of steps you will end up with exactly 1 wave which is the way the original dev of it wanted.
