### ISSUE TITLE
学習実行時のエラーについて

### ISSUE THREAD

**Issue by kaminaga528** [kohya-ss/sd-scripts#619]
READMEの内容通りに環境を構築し、Powershellで学習を実行したところ、エラーが発生して学習を行うことができませんでした。
以下にコマンドラインの実行文とエラーメッセージを記載いたしますので、解決方法をご教示いただけないでしょうか。

【実行文】
accelerate launch --num_cpu_threads_per_process 1 "train_network.py"
--pretrained_model_name_or_path="D:\kohya-ss\models\AnyLoRA_noVae_fp16-pruned.safetensors" 
--output_dir="D:\kohya-ss\outputs"
--output_name="sample1"
--dataset_config="D:\kohya-ss\train data\datasetconfig.toml"
--train_batch_size=4
--gradient_checkpointing
--max_train_epochs=20
--resolution="512,512"
--optimizer_type="AdamW"
--unet_lr=0.0025
--network_train_unet_only
--network_dim=128
--network_alpha=128
--network_args "conv_dim=128" "conv_alpha=128" "unit=4"
--enable_bucket
--bucket_no_upscale
--lr_scheduler="cosine_with_restarts"
--lr_scheduler_num_cycles=4
--lr_warmup_steps=0
--keep_tokens=1
--shuffle_caption
--caption_dropout_rate=0.05
--save_model_as="safetensors"
--clip_skip=2
--seed=42
--color_aug
--xformers
--mixed_precision="fp16"
--network_module="networks.dylora"
--persistent_data_loader_workers

【エラーメッセージ】
prepare tokenizer
Loading dataset config from D:\kohya-ss\train data\datasetconfig.toml
prepare images.
found directory D:\kohya-ss\train data\vii contains 50 image files
250 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 4
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "D:\kohya-ss\train data\vii"
    image_count: 50
    num_repeats: 5
    shuffle_caption: True
    keep_tokens: 1
    caption_dropout_rate: 0.05
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: True
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: None
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 245.55it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 250
mean ar error (without repeats): 0.0
preparing accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: D:\kohya-ss\models\AnyLoRA_noVae_fp16-pruned.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\kohya-ss\sd-scripts\venv\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "D:\kohya-ss\sd-scripts\venv\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\kohya-ss\sd-scripts\venv\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\kohya-ss\sd-scripts\venv\lib\site-packages\transformers\modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
UnicodeDecodeError: 'cp932' codec can't decode byte 0x86 in position 346: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\kohya-ss\sd-scripts\train_network.py", line 873, in <module>
    train(args)
  File "D:\kohya-ss\sd-scripts\train_network.py", line 168, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "D:\kohya-ss\sd-scripts\library\train_util.py", line 3149, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "D:\kohya-ss\sd-scripts\library\train_util.py", line 3115, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "D:\kohya-ss\sd-scripts\library\model_util.py", line 904, in load_models_from_stable_diffusion_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)
  File "D:\kohya-ss\sd-scripts\venv\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\kohya-ss\sd-scripts\venv\lib\site-packages\transformers\modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\snzw5/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at 'C:\Users\snzw5/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
Traceback (most recent call last):
  File "C:\Users\snzw5\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\snzw5\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya-ss\sd-scripts\venv\scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya-ss\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya-ss\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\kohya-ss\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya-ss\\sd-scripts\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=D:\\kohya-ss\\models\\AnyLoRA_noVae_fp16-pruned.safetensors', '--output_dir=D:\\kohya-ss\\outputs', '--output_name=sample1', '--dataset_config=D:\\kohya-ss\\train data\\datasetconfig.toml', '--train_batch_size=4', '--gradient_checkpointing', '--max_train_epochs=20', '--resolution=512,512', '--optimizer_type=AdamW', '--unet_lr=0.0025', '--network_train_unet_only', '--network_dim=128', '--network_alpha=128', '--network_args', 'conv_dim=128', 'conv_alpha=128', 'unit=4', '--enable_bucket', '--bucket_no_upscale', '--lr_scheduler=cosine_with_restarts', '--lr_scheduler_num_cycles=4', '--lr_warmup_steps=0', '--keep_tokens=1', '--shuffle_caption', '--caption_dropout_rate=0.05', '--save_model_as=safetensors', '--clip_skip=2', '--seed=42', '--color_aug', '--xformers', '--mixed_precision=fp16', '--network_module=networks.dylora', '--persistent_data_loader_workers']' returned non-zero exit status 1.

素人質問で大変恐縮ですが、どうぞよろしくお願いいたします。

**Comment by Ojoxux** [comment]
ff外から失礼します。
同じ状況なのですがどのように改善しましたでしょうか。
