### ISSUE TITLE
[SDXL] sdxl_train_network.py --cache_latentsで画像が読み込めないエラー

### ISSUE THREAD

**Issue by iKora128** [kohya-ss/sd-scripts#636]
マイナーエラーですが他の人も同じ様になるかもしれないので書き残しておきます
おそらく1024pxの解像度になり、横長（縦横比：16/9以上）の画像がキャッシュできない問題
I know this is a minor error, but I thought I'd leave it here in case others are experiencing the same thing
Cannot cache some images with a resolution of 1024px (aspect ratio: 16/9 or greater causes this problem)

【エラー内容】
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /sd-scripts-sdxl/sdxl_train_network.py:167 in <module>                                 │
│                                                                                                  │
│   164 │   args = train_util.read_config_from_file(args, parser)                                  │
│   165 │                                                                                          │
│   166 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 167 │   trainer.train(args)                                                                    │
│   168                                                                                            │
│                                                                                                  │
│ /sd-scripts-sdxl/train_network.py:250 in train                                         │
│                                                                                                  │
│   247 │   │   │   vae.requires_grad_(False)                                                      │
│   248 │   │   │   vae.eval()                                                                     │
│   249 │   │   │   with torch.no_grad():                                                          │
│ ❱ 250 │   │   │   │   train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_l   │
│   251 │   │   │   vae.to("cpu")                                                                  │
│   252 │   │   │   if torch.cuda.is_available():                                                  │
│   253 │   │   │   │   torch.cuda.empty_cache()                                                   │
│                                                                                                  │
│ /sd-scripts-sdxl/library/train_util.py:1730 in cache_latents                           │
│                                                                                                  │
│   1727 │   def cache_latents(self, vae, vae_batch_size=1, cache_to_disk=False, is_main_process=  │
│   1728 │   │   for i, dataset in enumerate(self.datasets):                                       │
│   1729 │   │   │   print(f"[Dataset {i}]")                                                       │
│ ❱ 1730 │   │   │   dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)    │
│   1731 │                                                                                         │
│   1732 │   def is_latent_cacheable(self) -> bool:                                                │
│   1733 │   │   return all([dataset.is_latent_cacheable() for dataset in self.datasets])          │
│                                                                                                  │
│ /sd-scripts-sdxl/library/train_util.py:918 in cache_latents                            │
│                                                                                                  │
│    915 │   │   │   for info, latent in zip(batch, latents):                                      │
│    916 │   │   │   │   # check NaN                                                               │
│    917 │   │   │   │   if torch.isnan(latents).any():                                            │
│ ❱  918 │   │   │   │   │   raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")  │
│    919 │   │   │   │                                                                             │
│    920 │   │   │   │   if cache_to_disk:                                                         │
│    921 │   │   │   │   │   save_latents_to_disk(info.latents_npz, latent, info.latents_original  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

【対症療法】
```
import os
from PIL import Image

image_folder = '/path/to/your_folder'

target_ratio = 16 / 9

for filename in os.listdir(image_folder):
    if filename.endswith('.jpg') or filename.endswith('.png'):
        file_path = os.path.join(image_folder, filename)

        try:
            image = Image.open(file_path)
            width, height = image.size

            ratio = width / height

            if ratio >= target_ratio:
                print('Remove image:', filename)
                os.remove(file_path)
        except Exception as e:
            print('Error with file:', file_path, str(e))
```

とりあえずの対処法として縦横比16/9以上の画像を取り除きました
datasetが少ない場合は、16/9以上のときに横をクロップするなども対症療法になると思います
For the time being, I have removed images with an aspect ratio of 16/9 or higher
If you have a small dataset, you may want to crop the sides when the ratio is 16/9 or higher

**Comment by iKora128** [comment]
自分の環境依存の可能性と、シンプルに16/9のせいではないかもしれないので検証中です

**Comment by hushaoqing** [comment]
```
--no_half_vae: Disable the half-precision (mixed-precision) VAE. VAE for SDXL seems to produce NaNs in some cases. This option is useful to avoid the NaNs.
```
It seems like caused by `half_vae`

**Comment by Humanoidme** [comment]
how did you fix it ?

**Comment by liuzhao6322** [comment]
no_half_vae = true
