### ISSUE TITLE
Feature: Print() where captions are being sourced from for clarity

### ISSUE THREAD

**Issue by thojmr** [kohya-ss/sd-scripts#66]
Hey again.  Today I realized that captions can be sourced from 3 different locations, but we can't tell where from the training log.

- metadata file
- directory name
- captions file

There is currently no distinction in the logs which source the captions are coming from.  It would be great to have a simple print line that states this clearly, to make sure you are training on the correct captions.  

Ex: Earlier I was training LoRA Dreambooth and was accidentally using directory name captions instead of captions file, but had no idea until training was done.

**Comment by lolxdmainkaisemaanlu** [comment]
> Hey again. Today I realized that captions can be sourced from 3 different locations, but we can't tell where from the training log.
> 
> * metadata file
> * directory name
> * captions file
> 
> There is currently no distinction in the logs which source the captions are coming from. It would be great to have a simple print line that states this clearly, to make sure you are training on the correct captions.
> 
> Ex: Earlier I was training LoRA Dreambooth and was accidentally using directory name captions instead of captions file, but had no idea until training was done.

Hey. I think i'm having a similar issue where I think the directory name is being used instead of the captions file... and I don't know how to check it. If there is a simple way to know, it would be great if it's implemented.

Also it always says ' using dreambooth method ' even when i'm trying to use the finetune method. Is this a bug?

**Comment by thojmr** [comment]
The quick and dirty solution is to add this in `train_utils.py` within `load_dreambooth_dir()`
```py
if cap_for_img:
	print("Using image captions from text file")
elif init_flag:
	print("Using caption_by_folder name")
```

It will spam your log for a few seconds, but at least you know the answer
