### ISSUE TITLE
Is everything alright with block weights?

### ISSUE THREAD

**Issue by abetteridea** [kohya-ss/sd-scripts#674]
There are currently 3 arguments for block weights in LoRA training:

- down_lr_weight
- mid_lr_weight
- up_lr_weight

Not sure why they are called _up_ and _down_ instead of _IN_ and _OUT_, but that's not even the main issue. Both down and up lr weights require **12 values**. How is this possible when LoRA is divided into **17 blocks**?

The blocks are:
1 BASE
6 IN
1 MID
9 OUT

Are these different blocks?

If this needs to be fixed, so do _block_dims_ and _block_alphas_ (currently requiring **25 values**).

**Comment by abetteridea** [comment]
Got it!

So I guess only the first 6 and 9 numbers are used for weights in Standard LoRA? Or 6 and 9 last numbers?

down = IN, up = OUT?

**Comment by abetteridea** [comment]
Right, as @kohya-ss said in Releases log:

> if you do not expand to conv2d3x3, **some** blocks do not have LoRA, but please specify 25 values ​​for the argument for consistency.

I wonder which are the **some** blocks?

@zyd232 suggests this structure in https://github.com/kohya-ss/sd-scripts/issues/470

![image](https://github.com/kohya-ss/sd-scripts/assets/67851516/24806d06-ee0f-4441-a4bb-ed3002a4074c)

But I've been researching Stable Diffusion UNet architecture and can't find a proof anywhere :( Are these the missing (convolution) blocks in Standard LoRA?

**Comment by abetteridea** [comment]
Thank you so much!

**Comment by abetteridea** [comment]
Thank you so much!

**Comment by raynapolsky** [comment]
> The Stable Diffusion v1 U-Net has transformer blocks for IN01, IN02, IN04, IN05, IN07, IN08, MID, OUT03 to OUT11.
> 
> They correspond to the following keys in the state dict: `model.diffusion_model.input_blocks.1`, `model.diffusion_model.input_blocks.2` ... `model.diffusion_model.middle_block` ... `model.diffusion_model.output_blocks.3` ... `model.diffusion_model.output_blocks.11`.
> 
> IN00, IN03, IN06, IN09, IN10, IN11, OUT00, OUT01, OUT02 don't have transformer (which has Linear layers) and only have Conv2d layers.

Are things different in this scenario with SDXL?
