### ISSUE TITLE
SD XL 1.0 error

### ISSUE THREAD

**Issue by jellersby** [kohya-ss/sd-scripts#689]
Hello. I'm trying to train a LoRA using the SD XL 1.0 base checkpoint. I am using the "sdxl" branch of this repo.

With SD 1.5, this training set worked perfectly. Now I seem to be having trouble with SD XL 1.0.

I'm attaching the invocation and output as a file because it's a huge error message.

[sdxl1-error.txt](https://github.com/kohya-ss/sd-scripts/files/12190544/sdxl1-error.txt)

**Comment by Isotr0py** [comment]
Use `sdxl_train_network.py` instead.

**Comment by jellersby** [comment]
:facepalm: Whoops. Thank you!
