### ISSUE TITLE
SDXL Lora large size

### ISSUE THREAD

**Issue by jellersby** [kohya-ss/sd-scripts#695]
Hello! I trained my first SDXL lora using these scripts. I'm noticing that each lora checkpoint is about 1.3GB. Is that right? My SD 1.5 loras from the same dataset came out to about 288MB or so. So that's about a 4.5X increase in size. :sweat_smile:

**Comment by thojmr** [comment]
Yep, they are larger.  But you should try a much smaller dim size with sdxl anyway

**Comment by Panchovix** [comment]
I did use in the past 128 dim/128 alpha for SD1.5 based models, and the output were ~144MB.

Now with that same settings, it weights 650MB on SDXL models haha.

For now, I tested 64/64 and still seems to work fine (now about size 325MB)

All those with only unet.

I'm now testing 48/48 with unet and text encoder training, and the size seems to be 325MB as well.
