### ISSUE TITLE
Question about merging multiple LoRA weights of SDXL, any chance to get similar result like using multiple LoRA together in WebUI?

### ISSUE THREAD

**Issue by terrificdm** [kohya-ss/sd-scripts#868]
For example, I can get satisfied result when I use <lora:sample1:0.7> <lora:sample2:0.4> together in WebUI prompt(supposed lora:sample2 has stronger impact on result, so I need less impact). But when I used "sdxl_merge_lora.py" to merge those two LoRAs, it turned out that lora:sample2's impact overwhelmed lora:sample1, and lora:sample2 cannot be weakened too much even I adjusted parameter with "--ratios 1 0", it still had heavy influence on result.
My question is how can I get similar merging result with the one in WebUI? And why the "--ratios 1 0" cannot eliminate the impact from the second LoRA to zero?

BTW, just want to bring out that if we can use the way of using multiple LoRA together in WebUI to identify the merging result before doing the real merging, it will be much convenient. 

Merging script is as below:
`python ./networks/sdxl_merge_lora.py --save_precision bf16 --save_to ./lora_weight/lora-merged-0.7_0.4.safetensors --models ./lora_weight/lora_sample1.safetensors ./lora_weight/lora_sample2.safetensors --ratios 0.7 0.4 --concat --shuffle`

Thanks for your help.

**Comment by AI-Casanova** [comment]
Take out --concat and --shuffle

Take the square root of both ratios.

**Comment by terrificdm** [comment]
> Take out --concat and --shuffle
> 
> Take the square root of both ratios.

Thanks, it works. And can you elaborate a little about why it requires square root for both ratios?

**Comment by AI-Casanova** [comment]
During inference you're scaling the whole layer, the merge is scaling each key individually

0.7up @ 0.7down = 0.7²updown
√0.7up @ √0.7down = 0.7updown

Concat and shuffle might give you interesting results with a higher resulting file size, but won't be WYSIWYG

**Comment by terrificdm** [comment]
Understood, appreciated your elaboration.

**Comment by AI-Casanova** [comment]
Glad I could help
