### ISSUE TITLE
Question. Webp support 

### ISSUE THREAD

**Issue by dill-shower** [kohya-ss/sd-scripts#88]
Is there support for webp format for training images? Webp provides a smaller file size and better quality than jpg. And there are no jpeg artifacts that can degrade learning outcomes.

**Comment by anon-1337** [comment]
Yes, there is support for *.webp images.
https://github.com/kohya-ss/sd-scripts/blob/4c928c8d12e22181cb592a7bd12a97eb553b1731/library/train_util.py#L44
