### ISSUE TITLE
TypeError: Accelerator.accumulate() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by thojmr** [kohya-ss/sd-scripts#926]
I was testing the current code in the Dev branch for SDXL single text encoder training, and ran into this:
 `TypeError: Accelerator.accumulate() takes 2 positional arguments but 3 were given` When training Unet + Text encoder` 

This seems to be caused by this change:
`with accelerator.accumulate(training_models[0]):` -> `with accelerator.accumulate(*training_models):`
in [sdxl_train.py](https://github.com/kohya-ss/sd-scripts/commit/01d929ee2a3a76951f3a422f6db0b1a8a2ee41da#diff-92b449ad9a092c088a2cb7b37fe8794eac983ee8f3309684cb44873095511eeb)

I don't think it likes being passed multiple params like that, google suggests:
`with accelerator.accumulate(training_models[0]), accelerator.accumulate(training_models[1]), etc...` 

Thanks

**Comment by araleza** [comment]
The old version of Accelerate from a few months ago can't take a list of models, so it sounds like you've fetched the dev branch but not gotten its matching dependencies somehow.

**Comment by thojmr** [comment]
Ah yea, my docker build cached the requirements.txt file so no packages would have been updated.  Thanks for pointing this out.
