### ISSUE TITLE
Missing key(s) in state_dict: "text_model.embeddings.position_ids".

### ISSUE THREAD

**Issue by Davikar** [kohya-ss/sd-scripts#937]
Trying to extract a Lycoris with the lycoris_locon_extract script and I get the following error:

```
Traceback (most recent call last):
  File "C:\AI\kohya_ss\tools\lycoris_locon_extract.py", line 129, in <module>
    main()
  File "C:\AI\kohya_ss\tools\lycoris_locon_extract.py", line 98, in main
    db = load_models_from_stable_diffusion_checkpoint(args.is_v2, args.db_model)
  File "C:\AI\kohya_ss\venv\lib\site-packages\lycoris\kohya\model_utils.py", line 1060, in load_models_from_stable_diffusion_checkpoint
    info = text_model.load_state_dict(converted_text_encoder_checkpoint)
  File "C:\AI\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Missing key(s) in state_dict: "text_model.embeddings.position_ids".
```

Was run with: ./venv/Scripts/python.exe "tools\lycoris_locon_extract.py" --device cuda --mode fixed --safetensors
                         --linear_dim 128 --conv_dim 64 --sparsity 0.98 "C:/AI/models/Stable-diffusion/cyberrealistic_v33
                         fp32.safetensors" "C:/AI/Training/Lora/Models/FT/Model.safetensors"
                         "C:/AI/Training/Lora/Models/Lyco/Lycoris Model.safetensors"

(Run via the Kohya GUI by bmaltais).
The finetune has been trained via a different tool (OneTrainer).

**Comment by vladmandic** [comment]
its not as simple as that key is also dependent on ancient `transformers` being used - it doesn't exist in newer transformers and eventually even this repo will need to upgrade.
see <https://github.com/kohya-ss/sd-scripts/pull/687#issuecomment-1742139009>
