### ISSUE TITLE
Is there a pause button?

### ISSUE THREAD

**Issue by Ketorami** [kohya-ss/sd-scripts#99]
Is there a pause button? I can't find it I want to stop and then start training again.

**Comment by anon-1337** [comment]
Check `--save_state` and `--resume` arguments:
https://github.com/kohya-ss/sd-scripts/blob/4a1668fe3782c1f10af040558fd23433f671d5a5/library/train_util.py#L1063
https://github.com/kohya-ss/sd-scripts/blob/4a1668fe3782c1f10af040558fd23433f671d5a5/library/train_util.py#L1065

**Comment by Ketorami** [comment]
I'm sorry I don't understand how to save Let me type in CMD? I can't. I'm using .\gui.ps1 so I can't type anything. Can you tell me what I need to do? Where to use the command? I'm using Window.
